{-# OPTIONS --safe --with-K #-}

--------------------------------------------------------------------------------
-- Discharge module for `decode-rel-resp-≅ᴴ-atomic-compound-0E` from
-- `RespIso/AtomicCompound.agda`.
--
-- ## Goal
--
-- Given an atomic `f : HomTerm A B` (one of `id, λ⇒, λ⇐, ρ⇒, ρ⇐, α⇒,
-- α⇐, σ` — the Agen case is handled separately by edge-count
-- arithmetic) and a compound `g : HomTerm A B` (i.e. `_∘_` or `_⊗₁_`)
-- whose translation has zero edges, plus an iso `⟪ f ⟫ ≅ᴴ ⟪ g ⟫`,
-- show `decode-rel f ≈Term decode-rel g`.
--
-- ## Why `g` is "structural"
--
-- Edge counts are additive across `_∘_` and `_⊗₁_`:
--
--   * `nE ⟪ h ∘ k ⟫  = nE ⟪ h ⟫ + nE ⟪ k ⟫`
--   * `nE ⟪ h ⊗₁ k ⟫ = nE ⟪ h ⟫ + nE ⟪ k ⟫`
--
-- and `nE ⟪ Agen _ ⟫ ≡ 1`.  So `nE ⟪ g ⟫ ≡ 0` propagates inductively:
-- every sub-term of `g` has zero edges, which rules out every `Agen`
-- node anywhere inside `g`.  We encode this as the `Structural`
-- predicate below — a syntactic witness "no `Agen` subterm" — and
-- prove the equivalence `nE ⟪ g ⟫ ≡ 0  ↔  Structural g`.
--
-- Both `f` (a structural atomic constructor) and `g` (a structural
-- compound) therefore live in the fragment generated by
-- `id, λ⇒, λ⇐, ρ⇒, ρ⇐, α⇒, α⇐, σ` under `_∘_, _⊗₁_`.  At the level
-- of `FreeMonoidal` this is exactly the *coherence fragment*: the
-- symmetric monoidal coherence theorem (Mac Lane + braiding) says any
-- two morphisms of the same type in this fragment whose underlying
-- permutations agree are `≈Term`-equal.  The iso `⟪ f ⟫ ≅ᴴ ⟪ g ⟫`
-- forces the underlying permutations to agree (both hypergraphs have
-- 0 edges, so they are entirely characterised by their boundary
-- permutations, and the iso provides a φ matching dom/cod up to
-- relabelling).
--
-- Constructive discharge requires the symmetric-monoidal coherence
-- solver (the existing `Categories.MonoidalCoherence.Solver` covers
-- the Mac Lane fragment but not σ; see
-- `Hypergraph.Completeness.CoherenceSolver` for the current limit).
-- Pending that solver extension, we narrow the original postulate to
-- a `Structural`-restricted form whose hypothesis is exactly the
-- "symmetric monoidal coherence on the structural fragment" claim.
--
-- ## What this module exports
--
-- * `Structural`             — syntactic predicate "no `Agen` subterm".
-- * `nE-0→Structural`        — `nE ⟪ g ⟫ ≡ 0 → Structural g`,
--                              fully constructive.
-- * `Structural-coherence-≈Term`
--                            — the *narrowed* postulate: any two
--                              structural terms of the same type with
--                              isomorphic translations are `≈Term`-equal
--                              at the `FreeMonoidal` level (i.e. `f ≈Term g`
--                              directly, no `decode-rel`/`bridge` wrapping).
--                              This is exactly Mac Lane's symmetric
--                              monoidal coherence theorem on the
--                              `id, λ, ρ, α, σ`-fragment.
-- * `Structural-coherence`   — derived: `decode-rel f ≈Term decode-rel g`,
--                              obtained from `Structural-coherence-≈Term`
--                              by passing through `decode-roundtrip-rel`
--                              and the `bridge`-congruence.
-- * `decode-rel-resp-≅ᴴ-atomic-compound-0E` — the original lemma,
--                              derived from the above ingredients
--                              together with the `Atomic ⇒ Structural`
--                              fact.
--
-- ## Why this narrowing is strict
--
-- The original postulate had conclusion `decode-rel f ≈Term decode-rel g`,
-- whose unfolding involves `bridge`, `unflatten-flatten-≈`, and the
-- structural recursion of `decode-rel` through `∘` and `⊗₁`.  The
-- narrowed conclusion `f ≈Term g` lives purely in the free symmetric
-- monoidal category over the signature, with no decode plumbing — it
-- is exactly the statement of categorical coherence for the
-- non-generator (a.k.a. `Structural`) fragment.
--
-- The derivation back to the original form uses only existing
-- constructive lemmas:
--   * `decode-roundtrip-rel f : decode-rel f ≈Term bridge f`     (proved)
--   * `decode-roundtrip-rel g : decode-rel g ≈Term bridge g`     (proved)
--   * `bridge` is a congruence wrt `≈Term`                       (1-line proof)
-- so the original lemma is `decode-roundtrip-rel f ; bridge-cong ; sym (decode-roundtrip-rel g)`.
--------------------------------------------------------------------------------

open import Categories.APROP
open import Categories.APROP.Hypergraph.Solver.Signature using (APROPSignatureDec)

module Categories.APROP.Hypergraph.Completeness.DecodeRel.RespIso.Discharge.AtomicCompound0E
  (sig-dec : APROPSignatureDec) where

open APROPSignatureDec sig-dec using (sig)
open APROP sig
open import Categories.APROP.Hypergraph.Core using (Hypergraph)
open import Categories.APROP.Hypergraph.FromAPROP sig using (FlatGen; flatten)
open import Categories.APROP.Hypergraph.Translation sig using (⟪_⟫)
open import Categories.APROP.Hypergraph.Iso using (_≅ᴴ_)
open import Categories.APROP.Hypergraph.Completeness.DecodeAttempt sig
  using (bridge)
open import Categories.APROP.Hypergraph.Completeness.DecodeRel sig
  using (decode-rel; decode-roundtrip-rel)

open import Data.Empty using (⊥; ⊥-elim)
open import Data.List using (List; []; _∷_; _++_; length)
open import Data.Nat using (ℕ; zero; suc; _+_)
open import Data.Sum using (_⊎_; inj₁; inj₂)
open import Data.Unit using (⊤; tt)
open import Data.Vec using (Vec; lookup) renaming ([] to []ⱽ; _∷_ to _∷ⱽ_)
open import Data.Fin using (Fin; zero; suc)
open import Relation.Binary.PropositionalEquality
  using (_≡_; refl; sym; trans; cong; cong₂; subst; subst₂)
open APROPSignatureDec sig-dec using (_≟X_)
open import Relation.Nullary using (yes; no)
import Data.List.Relation.Binary.Permutation.Propositional as Perm
import Data.List.Relation.Binary.Permutation.Propositional.Properties as PermProp
open Perm using (_↭_)
open import Data.List.Relation.Unary.Any using (Any; here; there)
open import Data.List.Membership.Propositional using (_∈_)
open import Categories.Functor using (Functor)

private
  nE : Hypergraph FlatGen → ℕ
  nE = Hypergraph.nE

--------------------------------------------------------------------------------
-- `NoSigma`: predicate "no `σ` (and no `Agen`) subterm anywhere".
-- Morphisms satisfying `NoSigma` live in the Mac Lane fragment, where
-- coherence is fully constructive via
-- `Categories.MonoidalCoherence.Solver.solveM`.

data NoSigma : ∀ {A B} → HomTerm A B → Set where
  nosigma-id : ∀ {A} → NoSigma (id {A})
  nosigma-λ⇒ : ∀ {A} → NoSigma (λ⇒ {A})
  nosigma-λ⇐ : ∀ {A} → NoSigma (λ⇐ {A})
  nosigma-ρ⇒ : ∀ {A} → NoSigma (ρ⇒ {A})
  nosigma-ρ⇐ : ∀ {A} → NoSigma (ρ⇐ {A})
  nosigma-α⇒ : ∀ {A B C} → NoSigma (α⇒ {A} {B} {C})
  nosigma-α⇐ : ∀ {A B C} → NoSigma (α⇐ {A} {B} {C})
  nosigma-∘  : ∀ {A B C} {h : HomTerm B C} {k : HomTerm A B}
             → NoSigma h → NoSigma k
             → NoSigma (h ∘ k)
  nosigma-⊗  : ∀ {A B C D} {h : HomTerm A B} {k : HomTerm C D}
             → NoSigma h → NoSigma k
             → NoSigma (h ⊗₁ k)

--------------------------------------------------------------------------------
-- Constructive discharge plumbing for the σ-free case via
-- `Categories.MonoidalCoherence.Solver.solveM`.
--
-- We instantiate the Solver at the *target* monoidal category
-- `(FreeMonoidal, Monoidal-FreeMonoidal)` itself: use it as a *proof*
-- tool, not as an evaluator into another category.  The Vec
-- `vars : Vec ObjTerm n` provides the per-atom mapping; atom `Fin i`
-- in the solver's `FreeMonoidal` interprets as `lookup vars i`, an
-- `ObjTerm` of the surrounding APROP free monoidal category.
--
-- Encoder pipeline (constructive parts below):
--   1. `objAtoms : ObjTerm → List X` collects `Var x` atoms.
--   2. `idx : (xs : List X) (x : X) → Fin (length xs)` lookup
--      (using `_≟X_`); on miss returns the last slot (safe fallback,
--      not used in the well-typed branch).
--   3. `varsOf : List X → ∃ Vec ObjTerm` produces the encoder's Vec.
--
-- Bridging the solver's `Fin n`-based `FreeMonoidal` back to the
-- surrounding APROP `FreeMonoidal` (which is over `X` with `Symm`
-- variant) requires `subst`-plumbing through two distinct
-- `FreeMonoidal` instantiations.  We leave the bridge as a narrow
-- postulate `enc-faithful` below — strictly weaker than the original
-- `-noσ` claim because it is the *purely structural* soundness of the
-- Mac Lane encoder, no σ involved.

-- Collect `Var x` atoms from an ObjTerm.
objAtoms : ObjTerm → List X
objAtoms unit     = []
objAtoms (A ⊗₀ B) = objAtoms A ++ objAtoms B
objAtoms (Var x)  = x ∷ []

-- Index of x in xs (with safe fallback to `zero` of `Fin (suc (length xs))`).
idxFin : (xs : List X) (x : X) → Fin (suc (length xs))
idxFin []       x = zero
idxFin (y ∷ ys) x with x ≟X y
... | yes _ = zero
... | no  _ = suc (idxFin ys x)

-- Build a Vec of ObjTerm of length `suc (length xs)` from xs, padding
-- with `unit` at the sentinel slot.
varsVec : (xs : List X) → Vec ObjTerm (suc (length xs))
varsVec []       = unit ∷ⱽ []ⱽ
varsVec (x ∷ xs) = Var x ∷ⱽ varsVec xs

-- Instantiate the Mac Lane coherence solver at the surrounding
-- FreeMonoidal, with the per-pair Vec `varsVec (xsAll f g)`.
module _ {A B : ObjTerm} {f g : HomTerm A B} (nf : NoSigma f) (ng : NoSigma g) where

  -- Atoms that need to be in the Vec: those from A, B, and any
  -- intermediate types inside f, g.  For the Mac Lane fragment a
  -- conservative choice is `objAtoms A ++ objAtoms B` extended with
  -- atoms collected from each NoSigma sub-term's type indices.

  -- We collect via NoSigma so termination is on the structural witness.
  nosigmaAtoms : ∀ {A B} {h : HomTerm A B} → NoSigma h → List X
  nosigmaAtoms {A} {B} nosigma-id      = objAtoms A
  nosigmaAtoms (nosigma-λ⇒ {A'})       = objAtoms A'
  nosigmaAtoms (nosigma-λ⇐ {A'})       = objAtoms A'
  nosigmaAtoms (nosigma-ρ⇒ {A'})       = objAtoms A'
  nosigmaAtoms (nosigma-ρ⇐ {A'})       = objAtoms A'
  nosigmaAtoms (nosigma-α⇒ {A'} {B'} {C'}) =
    objAtoms A' ++ objAtoms B' ++ objAtoms C'
  nosigmaAtoms (nosigma-α⇐ {A'} {B'} {C'}) =
    objAtoms A' ++ objAtoms B' ++ objAtoms C'
  nosigmaAtoms (nosigma-∘ h k) = nosigmaAtoms h ++ nosigmaAtoms k
  nosigmaAtoms (nosigma-⊗ h k) = nosigmaAtoms h ++ nosigmaAtoms k

  xsAll : List X
  xsAll = objAtoms A ++ objAtoms B ++ nosigmaAtoms nf ++ nosigmaAtoms ng

  vars-fg : Vec ObjTerm (suc (length xsAll))
  vars-fg = varsVec xsAll

  -- Instantiate the Mac Lane coherence solver in the surrounding
  -- FreeMonoidal, using `vars-fg` as the per-atom interpretation.
  open import Categories.MonoidalCoherence using (module Solver)
  open import Categories.Category.Monoidal using (Monoidal)
  open Monoidal Monoidal-FreeMonoidal using () renaming () public

  module S = Solver
    record { U = FreeMonoidal ; monoidal = Monoidal-FreeMonoidal }
    {n = suc (length xsAll)} vars-fg


  -- Structural encoder: ObjTerm → S.ObjTerm.  Atoms are indexed via
  -- `idxFin xsAll`; the sentinel slot (`unit`) catches misses but
  -- well-typed encoding never lands there.
  enc-Obj : ObjTerm → S.ObjTerm
  enc-Obj unit     = S.unit
  enc-Obj (P ⊗₀ Q) = enc-Obj P S.⊗₀ enc-Obj Q
  enc-Obj (Var x)  = S.Var (idxFin xsAll x)

  -- Structural encoder on HomTerms: NoSigma → S.HomTerm.  Defined by
  -- structural recursion on the `NoSigma` witness; each clause maps
  -- the APROP-side constructor to its solver-side counterpart.
  enc-Hom : ∀ {P Q} {h : HomTerm P Q}
          → NoSigma h
          → S.HomTerm (enc-Obj P) (enc-Obj Q)
  enc-Hom nosigma-id      = S.id
  enc-Hom nosigma-λ⇒      = S.λ⇒
  enc-Hom nosigma-λ⇐      = S.λ⇐
  enc-Hom nosigma-ρ⇒      = S.ρ⇒
  enc-Hom nosigma-ρ⇐      = S.ρ⇐
  enc-Hom nosigma-α⇒      = S.α⇒
  enc-Hom nosigma-α⇐      = S.α⇐
  enc-Hom (nosigma-∘ h k) = enc-Hom h S.∘ enc-Hom k
  enc-Hom (nosigma-⊗ h k) = enc-Hom h S.⊗₁ enc-Hom k

  -- The Solver's interpretation `⟦ ef ⟧₁` lives in APROP's
  -- FreeMonoidal: source `Functor.F₀ S.freeFunctor (enc-Obj P) : ObjTerm`, target similarly.
  -- `solveM ef eg : ⟦ ef ⟧₁ ≈Term ⟦ eg ⟧₁` is precisely an APROP-side
  -- `_≈Term_` equation (Mac Lane coherence in the σ-free fragment).
  --
  -- To convert this into `f ≈Term g`, we need encoder-soundness:
  -- `f ≈Term Functor.F₁ S.freeFunctor (enc-Hom nf)` and similarly for `g` (modulo
  -- equality `Functor.F₀ S.freeFunctor (enc-Obj A) ≡ A`).  Both lemmas are pure structural
  -- recursions, but discharging them requires bridging two
  -- `FreeMonoidal` instantiations and aligning `subst`s — left as a
  -- narrow self-contained postulate.

  -- Encoded pair (constructive output of the encoder).
  ef-built : S.HomTerm (enc-Obj A) (enc-Obj B)
  ef-built = enc-Hom nf

  eg-built : S.HomTerm (enc-Obj A) (enc-Obj B)
  eg-built = enc-Hom ng

  -- `solveM` discharges Mac Lane coherence in the σ-free Fin-indexed
  -- FreeMonoidal.  The return type uses the Solver's private
  -- `FreeFunctor` interpretation `⟦_⟧₁` (not re-exported by `Solver`
  -- with `public`).  We name the result and let Agda infer the type.
  --
  -- This call is the *constructive heart* of the σ-free coherence
  -- discharge: at this point all the categorical work is done.  The
  -- remaining work (`enc-bridge-to-f≈g`) is purely the encoder's
  -- soundness reflection back into APROP's `_≈Term_`.
  solver-result : _
  solver-result = S.solveM ef-built eg-built

  --------------------------------------------------------------------------------
  -- Encoder soundness: `Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P` when atoms of P live in xsAll.
  --
  -- Below, `lookup-mem` is the heart: when `x ∈ xs` (witnessed by `Any`),
  -- the encoder round-trips `x` to `Var x`.  Then `enc-Obj-sound` is a
  -- straight structural induction on `P`, using `lookup-mem` at each
  -- `Var` leaf.

  -- Helper: lookup at the index produced by `idxFin` round-trips through
  -- the var-vector.  By induction on the membership witness.
  lookup-mem
    : (xs : List X) {x : X} (m : x ∈ xs)
    → lookup (varsVec xs) (idxFin xs x) ≡ Var x
  lookup-mem (y ∷ ys) {x} (here refl) with x ≟X y
  ... | yes _    = refl
  ... | no  x≢y  = ⊥-elim (x≢y refl)
  lookup-mem (y ∷ ys) {x} (there m) with x ≟X y
  ... | yes refl = refl
  ... | no  _    = lookup-mem ys m

  -- A `Var` atom appearing inside `objAtoms P` is exactly an atom of P.
  -- For our use we need to convert "every atom of P is in xsAll" into
  -- the relevant membership witness.  We work with the simple sublist
  -- inclusion `objAtoms P ⊆ xsAll`.

  _⊆L_ : List X → List X → Set
  xs ⊆L ys = ∀ {x} → x ∈ xs → x ∈ ys

  -- Soundness of the object encoder, parameterised by membership.
  enc-Obj-sound
    : (P : ObjTerm)
    → objAtoms P ⊆L xsAll
    → Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P
  enc-Obj-sound unit       _   = refl
  enc-Obj-sound (P ⊗₀ Q) sub =
    cong₂ _⊗₀_
      (enc-Obj-sound P (λ m → sub (∈-++ˡ m)))
      (enc-Obj-sound Q (λ m → sub (∈-++ʳ (objAtoms P) m)))
    where
      ∈-++ˡ : ∀ {x ys zs} → x ∈ ys → x ∈ (ys ++ zs)
      ∈-++ˡ (here px)  = here px
      ∈-++ˡ (there m)  = there (∈-++ˡ m)
      ∈-++ʳ : ∀ {x} (ys : List X) {zs} → x ∈ zs → x ∈ (ys ++ zs)
      ∈-++ʳ []        m = m
      ∈-++ʳ (y ∷ ys') m = there (∈-++ʳ ys' m)
  enc-Obj-sound (Var x) sub = lookup-mem xsAll (sub (here refl))

  -- xsAll begins with `objAtoms A`, so atoms of A are trivially in xsAll.
  -- Similarly, after the A-prefix it has objAtoms B, then the two
  -- nosigmaAtoms blocks.

  ∈-++ˡ : ∀ {x} {ys zs : List X} → x ∈ ys → x ∈ (ys ++ zs)
  ∈-++ˡ (here px)  = here px
  ∈-++ˡ (there m)  = there (∈-++ˡ m)
  ∈-++ʳ : ∀ {x} (ys : List X) {zs : List X} → x ∈ zs → x ∈ (ys ++ zs)
  ∈-++ʳ []        m = m
  ∈-++ʳ (y ∷ ys') m = there (∈-++ʳ ys' m)

  -- objAtoms A is the first block of xsAll.
  A-atoms-in-xsAll : objAtoms A ⊆L xsAll
  A-atoms-in-xsAll m = ∈-++ˡ m

  B-atoms-in-xsAll : objAtoms B ⊆L xsAll
  B-atoms-in-xsAll m = ∈-++ʳ (objAtoms A) (∈-++ˡ m)

  enc-Obj-sound-A : Functor.F₀ S.freeFunctor (enc-Obj A) ≡ A
  enc-Obj-sound-A = enc-Obj-sound A A-atoms-in-xsAll

  enc-Obj-sound-B : Functor.F₀ S.freeFunctor (enc-Obj B) ≡ B
  enc-Obj-sound-B = enc-Obj-sound B B-atoms-in-xsAll

  --------------------------------------------------------------------------------
  -- Inclusion of every NoSigma sub-term's atoms into xsAll.  We thread
  -- this as a `Path` from a witness inside `nf`/`ng` down to xsAll.
  --
  -- For ∘/⊗ we use the fact that `nosigmaAtoms` is additive across
  -- composition/tensor (the witness lives in either the left or right
  -- branch).  But really, only the LEAF nodes need direct membership —
  -- internal ∘/⊗ nodes inherit recursively.  We therefore phrase
  -- `enc-Hom-sound` as: given that the source and target objAtoms are
  -- in xsAll, the encoder is sound; and at ∘/⊗ we recurse with the
  -- intermediate type's atoms in xsAll (provided by the structural
  -- shape of nf, ng).

  -- For `nosigma-∘ {B = M} h k` we need atoms of M in xsAll.  In the
  -- `nf`/`ng` witnesses, the intermediate type M's atoms appear in the
  -- corresponding sub-term's nosigmaAtoms (every leaf inside h has type
  -- with M-related atoms covered).  Rather than thread the inclusion
  -- explicitly, we expose a structural-induction-friendly form that
  -- carries the source/target inclusions as parameters.

  --------------------------------------------------------------------------------
  -- Hom encoder soundness (≈Term form, parameterised by atom-inclusions
  -- for the source and target types).
  --
  -- We package `Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P` and similarly for Q, then state:
  --
  --   subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nh)) ≡ h
  --
  -- By induction on nh.  Base cases are immediate because
  -- `S.⟦ S.id ⟧₁`, `S.⟦ S.λ⇒ ⟧₁`, ..., reduce definitionally to the
  -- APROP-side constructors `id`, `λ⇒`, ..., at the encoded source/
  -- target objects.  The `subst₂` collapses to `refl` after K-style
  -- reasoning on ObjTerm equality (justified by ObjTerm having
  -- decidable equality, hence UIP).

  -- For the ∘/⊗ inductive cases we additionally need atom-inclusion
  -- for the intermediate type; these come from the structural form
  -- of the NoSigma sub-witness's source/target leaves.

  -- We expose only the specialised forms we need: encoder soundness
  -- specifically at f and at g (both `HomTerm A B`).  Their proofs use
  -- the postulate `enc-Hom-≡-up-to-subst` below — the *narrowest*
  -- remaining gap, strictly about `subst` plumbing through a
  -- definitionally-trivial encoder.

  -- Discharge of `enc-Hom-sound-id`: any NoSigma term h is transported
  -- to itself by the encoder–decoder round-trip.  Proof: induction on
  -- nh.  For each structural constructor, `F₁ S.freeFunctor (enc-Hom …)`
  -- reduces definitionally to the corresponding APROP-side constructor,
  -- and the subst₂ collapses via UIP on ObjTerm (provable from decidable
  -- atom equality `_≟-ObjTerm_`) combined with J on a single object-arg
  -- equality (per constructor).
  private
    import Axiom.UniquenessOfIdentityProofs as UIP-mod
    open APROPSignatureDec sig-dec using (_≟-ObjTerm_)
    module ObjTerm-UIP-mod = UIP-mod.Decidable⇒UIP _≟-ObjTerm_

    ObjTerm-UIP : ∀ {A B : ObjTerm} (p q : A ≡ B) → p ≡ q
    ObjTerm-UIP = ObjTerm-UIP-mod.≡-irrelevant

    -- Per-constructor coercion lemmas.  Each takes the source/target
    -- substitutions plus the underlying argument equalities (derived
    -- from sP/sQ via injectivity of `_⊗₀_`), and reduces `subst₂`
    -- through the constructor to refl.

    id-coerce
      : ∀ {X Y : ObjTerm} (p q : X ≡ Y)
      → subst₂ HomTerm p q (id {X}) ≡ id {Y}
    id-coerce refl q with ObjTerm-UIP q refl
    ... | refl = refl

    λ⇒-coerce
      : ∀ {X Y : ObjTerm} (p : unit ⊗₀ X ≡ unit ⊗₀ Y) (q : X ≡ Y)
      → subst₂ HomTerm p q (λ⇒ {X}) ≡ λ⇒ {Y}
    λ⇒-coerce p refl with ObjTerm-UIP p refl
    ... | refl = refl

    λ⇐-coerce
      : ∀ {X Y : ObjTerm} (p : X ≡ Y) (q : unit ⊗₀ X ≡ unit ⊗₀ Y)
      → subst₂ HomTerm p q (λ⇐ {X}) ≡ λ⇐ {Y}
    λ⇐-coerce refl q with ObjTerm-UIP q refl
    ... | refl = refl

    ρ⇒-coerce
      : ∀ {X Y : ObjTerm} (p : X ⊗₀ unit ≡ Y ⊗₀ unit) (q : X ≡ Y)
      → subst₂ HomTerm p q (ρ⇒ {X}) ≡ ρ⇒ {Y}
    ρ⇒-coerce p refl with ObjTerm-UIP p refl
    ... | refl = refl

    ρ⇐-coerce
      : ∀ {X Y : ObjTerm} (p : X ≡ Y) (q : X ⊗₀ unit ≡ Y ⊗₀ unit)
      → subst₂ HomTerm p q (ρ⇐ {X}) ≡ ρ⇐ {Y}
    ρ⇐-coerce refl q with ObjTerm-UIP q refl
    ... | refl = refl

    α⇒-coerce
      : ∀ {X Y Z X' Y' Z' : ObjTerm}
          (sX : X ≡ X') (sY : Y ≡ Y') (sZ : Z ≡ Z')
          (p : (X ⊗₀ Y) ⊗₀ Z ≡ (X' ⊗₀ Y') ⊗₀ Z')
          (q : X ⊗₀ (Y ⊗₀ Z) ≡ X' ⊗₀ (Y' ⊗₀ Z'))
      → subst₂ HomTerm p q (α⇒ {X} {Y} {Z}) ≡ α⇒ {X'} {Y'} {Z'}
    α⇒-coerce refl refl refl p q
      with ObjTerm-UIP p refl | ObjTerm-UIP q refl
    ... | refl | refl = refl

    α⇐-coerce
      : ∀ {X Y Z X' Y' Z' : ObjTerm}
          (sX : X ≡ X') (sY : Y ≡ Y') (sZ : Z ≡ Z')
          (p : X ⊗₀ (Y ⊗₀ Z) ≡ X' ⊗₀ (Y' ⊗₀ Z'))
          (q : (X ⊗₀ Y) ⊗₀ Z ≡ (X' ⊗₀ Y') ⊗₀ Z')
      → subst₂ HomTerm p q (α⇐ {X} {Y} {Z}) ≡ α⇐ {X'} {Y'} {Z'}
    α⇐-coerce refl refl refl p q
      with ObjTerm-UIP p refl | ObjTerm-UIP q refl
    ... | refl | refl = refl

    -- Injectivity of `_⊗₀_`.
    ⊗-injˡ : ∀ {A A' B B' : ObjTerm} → (A ⊗₀ B) ≡ (A' ⊗₀ B') → A ≡ A'
    ⊗-injˡ refl = refl

    ⊗-injʳ : ∀ {A A' B B' : ObjTerm} → (A ⊗₀ B) ≡ (A' ⊗₀ B') → B ≡ B'
    ⊗-injʳ refl = refl

    -- Push subst₂ through `_∘_`: it preserves composition, factored
    -- through an intermediate type's equality `sM`.
    ∘-coerce
      : ∀ {X M Y X' M' Y' : ObjTerm}
          (h : HomTerm M Y) (k : HomTerm X M)
          (h' : HomTerm M' Y') (k' : HomTerm X' M')
          (sX : X ≡ X') (sM : M ≡ M') (sY : Y ≡ Y')
          (p : X ≡ X') (q : Y ≡ Y')
      → subst₂ HomTerm sM sY h ≡ h'
      → subst₂ HomTerm sX sM k ≡ k'
      → subst₂ HomTerm p q (h ∘ k) ≡ h' ∘ k'
    ∘-coerce h k h' k' refl refl refl p q eh ek
      with ObjTerm-UIP p refl | ObjTerm-UIP q refl
    ... | refl | refl rewrite eh | ek = refl

    -- Push subst₂ through `_⊗₁_`.
    ⊗-coerce
      : ∀ {A B C D A' B' C' D' : ObjTerm}
          (h : HomTerm A B) (k : HomTerm C D)
          (h' : HomTerm A' B') (k' : HomTerm C' D')
          (sA : A ≡ A') (sB : B ≡ B') (sC : C ≡ C') (sD : D ≡ D')
          (p : A ⊗₀ C ≡ A' ⊗₀ C') (q : B ⊗₀ D ≡ B' ⊗₀ D')
      → subst₂ HomTerm sA sB h ≡ h'
      → subst₂ HomTerm sC sD k ≡ k'
      → subst₂ HomTerm p q (h ⊗₁ k) ≡ h' ⊗₁ k'
    ⊗-coerce h k h' k' refl refl refl refl p q eh ek
      with ObjTerm-UIP p refl | ObjTerm-UIP q refl
    ... | refl | refl rewrite eh | ek = refl

  -- Inclusion bookkeeping: every NoSigma sub-term's source and target
  -- objAtoms are contained in its `nosigmaAtoms`.  Combined with an
  -- outer "this nh's nosigmaAtoms ⊆ xsAll" hypothesis, we can recover
  -- the intermediate-type equality at every recursive step.

  private
    ⊆L-trans : ∀ {xs ys zs : List X} → xs ⊆L ys → ys ⊆L zs → xs ⊆L zs
    ⊆L-trans f g m = g (f m)

    ⊆L-++ˡ : ∀ {xs ys zs : List X} → xs ⊆L ys → xs ⊆L (ys ++ zs)
    ⊆L-++ˡ f m = ∈-++ˡ (f m)

    ⊆L-++ʳ : ∀ {xs} (ys : List X) {zs : List X} → xs ⊆L zs → xs ⊆L (ys ++ zs)
    ⊆L-++ʳ ys f m = ∈-++ʳ ys (f m)

    ⊆L-refl : ∀ {xs : List X} → xs ⊆L xs
    ⊆L-refl m = m

    objAtoms-⊗₀ : ∀ A B → objAtoms (A ⊗₀ B) ⊆L (objAtoms A ++ objAtoms B)
    objAtoms-⊗₀ A B = ⊆L-refl

    -- src-atoms / tgt-atoms of a NoSigma witness are included in its nosigmaAtoms.
    nosigmaAtoms-src⊆ : ∀ {P Q} {h : HomTerm P Q} (nh : NoSigma h)
                      → objAtoms P ⊆L nosigmaAtoms nh
    nosigmaAtoms-tgt⊆ : ∀ {P Q} {h : HomTerm P Q} (nh : NoSigma h)
                      → objAtoms Q ⊆L nosigmaAtoms nh

    nosigmaAtoms-src⊆ (nosigma-id {A}) = ⊆L-refl
    -- src of λ⇒ is unit ⊗₀ A; objAtoms = [] ++ objAtoms A = objAtoms A
    nosigmaAtoms-src⊆ (nosigma-λ⇒ {A}) m = m
    nosigmaAtoms-src⊆ (nosigma-λ⇐ {A}) m = m
    nosigmaAtoms-src⊆ (nosigma-ρ⇒ {A}) {x} m = aux (objAtoms A) m
      where
        aux : ∀ (xs : List X) {x} → x ∈ (xs ++ []) → x ∈ xs
        aux []       ()
        aux (y ∷ ys) (here px) = here px
        aux (y ∷ ys) (there m') = there (aux ys m')
    nosigmaAtoms-src⊆ (nosigma-ρ⇐ {A}) m = m
    nosigmaAtoms-src⊆ (nosigma-α⇒ {A} {B} {C}) m = α⇒-src m
      where
        -- src = (A⊗B)⊗C, objAtoms = (objAtoms A ++ objAtoms B) ++ objAtoms C
        -- tgt of nosigmaAtoms = objAtoms A ++ objAtoms B ++ objAtoms C
        α⇒-src : ((objAtoms A ++ objAtoms B) ++ objAtoms C) ⊆L (objAtoms A ++ objAtoms B ++ objAtoms C)
        α⇒-src m' = ++-assoc-→ (objAtoms A) (objAtoms B) (objAtoms C) m'
          where
            ++-assoc-→ : ∀ (xs ys zs : List X) {x}
                       → x ∈ ((xs ++ ys) ++ zs) → x ∈ (xs ++ ys ++ zs)
            ++-assoc-→ []       ys zs m'' = m''
            ++-assoc-→ (x ∷ xs') ys zs (here px) = here px
            ++-assoc-→ (x ∷ xs') ys zs (there m'') = there (++-assoc-→ xs' ys zs m'')
    nosigmaAtoms-src⊆ (nosigma-α⇐ {A} {B} {C}) m = m  -- src = A⊗(B⊗C), same flattening
    nosigmaAtoms-src⊆ (nosigma-∘ h k) = ⊆L-++ʳ (nosigmaAtoms h) (nosigmaAtoms-src⊆ k)
    nosigmaAtoms-src⊆ (nosigma-⊗ {A} {B} {C} {D} h k) =
      atoms-split-src {A} {C} (nosigmaAtoms-src⊆ h) (nosigmaAtoms-src⊆ k)
      where
        -- Generic: split membership across `xs ++ ys`.
        split-∈ : ∀ {x} (xs ys : List X) → x ∈ (xs ++ ys) → (x ∈ xs) ⊎ (x ∈ ys)
        split-∈ []       ys m            = inj₂ m
        split-∈ (y ∷ ys') zs (here px)   = inj₁ (here px)
        split-∈ (y ∷ ys') zs (there m')  with split-∈ ys' zs m'
        ... | inj₁ m'' = inj₁ (there m'')
        ... | inj₂ m'' = inj₂ m''

        atoms-split-src
          : ∀ {A C : ObjTerm} {hA hB : List X}
          → objAtoms A ⊆L hA → objAtoms C ⊆L hB
          → objAtoms (A ⊗₀ C) ⊆L (hA ++ hB)
        atoms-split-src {A} {C} {hA} {hB} fa fc {x} m with split-∈ (objAtoms A) (objAtoms C) m
        ... | inj₁ mA = ∈-++ˡ (fa mA)
        ... | inj₂ mC = ∈-++ʳ hA (fc mC)

    nosigmaAtoms-tgt⊆ (nosigma-id {A}) = ⊆L-refl
    nosigmaAtoms-tgt⊆ (nosigma-λ⇒ {A}) = ⊆L-refl
    nosigmaAtoms-tgt⊆ (nosigma-λ⇐ {A}) m = m
    nosigmaAtoms-tgt⊆ (nosigma-ρ⇒ {A}) = ⊆L-refl
    nosigmaAtoms-tgt⊆ (nosigma-ρ⇐ {A}) {x} m = aux (objAtoms A) m
      where
        aux : ∀ (xs : List X) {x} → x ∈ (xs ++ []) → x ∈ xs
        aux []       ()
        aux (y ∷ ys) (here px) = here px
        aux (y ∷ ys) (there m') = there (aux ys m')
    nosigmaAtoms-tgt⊆ (nosigma-α⇒ {A} {B} {C}) m = m  -- tgt is A⊗(B⊗C)
    nosigmaAtoms-tgt⊆ (nosigma-α⇐ {A} {B} {C}) m = α⇐-tgt m
      where
        α⇐-tgt : ((objAtoms A ++ objAtoms B) ++ objAtoms C) ⊆L (objAtoms A ++ objAtoms B ++ objAtoms C)
        α⇐-tgt m' = ++-assoc-→ (objAtoms A) (objAtoms B) (objAtoms C) m'
          where
            ++-assoc-→ : ∀ (xs ys zs : List X) {x}
                       → x ∈ ((xs ++ ys) ++ zs) → x ∈ (xs ++ ys ++ zs)
            ++-assoc-→ []       ys zs m'' = m''
            ++-assoc-→ (x ∷ xs') ys zs (here px) = here px
            ++-assoc-→ (x ∷ xs') ys zs (there m'') = there (++-assoc-→ xs' ys zs m'')
    nosigmaAtoms-tgt⊆ (nosigma-∘ h k) = ⊆L-++ˡ (nosigmaAtoms-tgt⊆ h)
    nosigmaAtoms-tgt⊆ (nosigma-⊗ {A} {B} {C} {D} h k) =
      atoms-split-tgt {B} {D} (nosigmaAtoms-tgt⊆ h) (nosigmaAtoms-tgt⊆ k)
      where
        split-∈ : ∀ {x} (xs ys : List X) → x ∈ (xs ++ ys) → (x ∈ xs) ⊎ (x ∈ ys)
        split-∈ []       ys m            = inj₂ m
        split-∈ (y ∷ ys') zs (here px)   = inj₁ (here px)
        split-∈ (y ∷ ys') zs (there m')  with split-∈ ys' zs m'
        ... | inj₁ m'' = inj₁ (there m'')
        ... | inj₂ m'' = inj₂ m''

        atoms-split-tgt
          : ∀ {B D : ObjTerm} {hA hB : List X}
          → objAtoms B ⊆L hA → objAtoms D ⊆L hB
          → objAtoms (B ⊗₀ D) ⊆L (hA ++ hB)
        atoms-split-tgt {B} {D} {hA} {hB} fa fc {x} m with split-∈ (objAtoms B) (objAtoms D) m
        ... | inj₁ mB = ∈-++ˡ (fa mB)
        ... | inj₂ mD = ∈-++ʳ hA (fc mD)

    -- Intermediate-type equality for the ∘ case: in `nosigma-∘ h k`,
    -- given an outer inclusion `nosigmaAtoms (nosigma-∘ h k) ⊆L xsAll`,
    -- the intermediate type M = tgt k = src h has objAtoms covered.
    inter-eq
      : ∀ {P Q} {h : HomTerm P Q} (nh : NoSigma h)
      → nosigmaAtoms nh ⊆L xsAll
      → Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P
    inter-eq {P} nh inc = enc-Obj-sound P (⊆L-trans (nosigmaAtoms-src⊆ nh) inc)

    inter-eq-tgt
      : ∀ {P Q} {h : HomTerm P Q} (nh : NoSigma h)
      → nosigmaAtoms nh ⊆L xsAll
      → Functor.F₀ S.freeFunctor (enc-Obj Q) ≡ Q
    inter-eq-tgt {Q = Q} nh inc = enc-Obj-sound Q (⊆L-trans (nosigmaAtoms-tgt⊆ nh) inc)

  -- The main lemma.  Now parameterised by an inclusion proof so we can
  -- access intermediate-type equalities in `∘` recursive cases.
  enc-Hom-sound-id-inc
    : ∀ {P Q} {h : HomTerm P Q} (nh : NoSigma h)
      (inc : nosigmaAtoms nh ⊆L xsAll)
      (sP : Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P)
      (sQ : Functor.F₀ S.freeFunctor (enc-Obj Q) ≡ Q)
    → subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nh)) ≡ h
  enc-Hom-sound-id-inc (nosigma-id {A})            inc sP sQ = id-coerce sP sQ
  enc-Hom-sound-id-inc (nosigma-λ⇒ {A})            inc sP sQ = λ⇒-coerce sP sQ
  enc-Hom-sound-id-inc (nosigma-λ⇐ {A})            inc sP sQ = λ⇐-coerce sP sQ
  enc-Hom-sound-id-inc (nosigma-ρ⇒ {A})            inc sP sQ = ρ⇒-coerce sP sQ
  enc-Hom-sound-id-inc (nosigma-ρ⇐ {A})            inc sP sQ = ρ⇐-coerce sP sQ
  enc-Hom-sound-id-inc (nosigma-α⇒ {A} {B} {C})    inc sP sQ =
    α⇒-coerce (⊗-injˡ (⊗-injˡ sP)) (⊗-injʳ (⊗-injˡ sP)) (⊗-injʳ sP) sP sQ
  enc-Hom-sound-id-inc (nosigma-α⇐ {A} {B} {C})    inc sP sQ =
    α⇐-coerce (⊗-injˡ sP) (⊗-injˡ (⊗-injʳ sP)) (⊗-injʳ (⊗-injʳ sP)) sP sQ
  enc-Hom-sound-id-inc (nosigma-∘ {A} {M} {C} h k) inc sP sQ =
    let
      inc-h : nosigmaAtoms h ⊆L xsAll
      inc-h m = inc (∈-++ˡ m)
      inc-k : nosigmaAtoms k ⊆L xsAll
      inc-k m = inc (∈-++ʳ (nosigmaAtoms h) m)
      sM : Functor.F₀ S.freeFunctor (enc-Obj M) ≡ M
      sM = inter-eq-tgt k inc-k  -- tgt of k = M
    in ∘-coerce _ _ _ _ sP sM sQ sP sQ
         (enc-Hom-sound-id-inc h inc-h sM sQ)
         (enc-Hom-sound-id-inc k inc-k sP sM)
  enc-Hom-sound-id-inc (nosigma-⊗ {A} {B} {C} {D} h k) inc sP sQ =
    let
      inc-h : nosigmaAtoms h ⊆L xsAll
      inc-h m = inc (∈-++ˡ m)
      inc-k : nosigmaAtoms k ⊆L xsAll
      inc-k m = inc (∈-++ʳ (nosigmaAtoms h) m)
    in ⊗-coerce _ _ _ _
         (⊗-injˡ sP) (⊗-injˡ sQ) (⊗-injʳ sP) (⊗-injʳ sQ) sP sQ
         (enc-Hom-sound-id-inc h inc-h (⊗-injˡ sP) (⊗-injˡ sQ))
         (enc-Hom-sound-id-inc k inc-k (⊗-injʳ sP) (⊗-injʳ sQ))

  -- Inclusions for the top-level nf and ng in xsAll = objAtoms A ++
  -- objAtoms B ++ nosigmaAtoms nf ++ nosigmaAtoms ng.
  private
    nf-inclusion : nosigmaAtoms nf ⊆L xsAll
    nf-inclusion m = ∈-++ʳ (objAtoms A) (∈-++ʳ (objAtoms B) (∈-++ˡ m))

    ng-inclusion : nosigmaAtoms ng ⊆L xsAll
    ng-inclusion m = ∈-++ʳ (objAtoms A) (∈-++ʳ (objAtoms B) (∈-++ʳ (nosigmaAtoms nf) m))

  -- Lift the propositional encoder-soundness into ≈Term.  Specialised
  -- to nh = nf and nh = ng (the only consumers), where the inclusion
  -- `nosigmaAtoms nh ⊆L xsAll` is structurally available.
  enc-Hom-sound-≈-nf
    : (sP : Functor.F₀ S.freeFunctor (enc-Obj A) ≡ A) (sQ : Functor.F₀ S.freeFunctor (enc-Obj B) ≡ B)
    → subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nf)) ≈Term f
  enc-Hom-sound-≈-nf sP sQ
    rewrite enc-Hom-sound-id-inc nf nf-inclusion sP sQ = ≈-Term-refl

  enc-Hom-sound-≈-ng
    : (sP : Functor.F₀ S.freeFunctor (enc-Obj A) ≡ A) (sQ : Functor.F₀ S.freeFunctor (enc-Obj B) ≡ B)
    → subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom ng)) ≈Term g
  enc-Hom-sound-≈-ng sP sQ
    rewrite enc-Hom-sound-id-inc ng ng-inclusion sP sQ = ≈-Term-refl

  -- The discharge of the σ-free Structural coherence postulate:
  -- combine encoder soundness with `solver-result`.  All three pieces
  -- live in `HomTerm A B` after the subst-transports of
  -- `enc-Obj-sound-{A,B}`.

  noσ-discharge : f ≈Term g
  noσ-discharge = ≈-Term-trans (≈-Term-sym sound-f)
                   (≈-Term-trans subst-eq sound-g)
    where
      sP = enc-Obj-sound-A
      sQ = enc-Obj-sound-B

      sound-f : subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nf)) ≈Term f
      sound-f = enc-Hom-sound-≈-nf sP sQ

      sound-g : subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom ng)) ≈Term g
      sound-g = enc-Hom-sound-≈-ng sP sQ

      -- Push solver-result through subst₂: subst₂ is a congruence
      -- for ≈Term (with the same indices on both sides).
      subst₂-cong-≈Term
        : ∀ {P Q P' Q'} (eP : P ≡ P') (eQ : Q ≡ Q')
          {h k : HomTerm P Q} → h ≈Term k
        → subst₂ HomTerm eP eQ h ≈Term subst₂ HomTerm eP eQ k
      subst₂-cong-≈Term refl refl eq = eq

      subst-eq
        : subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nf))
        ≈Term subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom ng))
      subst-eq = subst₂-cong-≈Term sP sQ solver-result

-- Discharge of the previously-postulated σ-free coherence claim, now
-- via the module-internal `noσ-discharge`.

Structural-coherence-≈Term-noσ
  : ∀ {A B} {f g : HomTerm A B}
  → NoSigma f → NoSigma g
  → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
  → f ≈Term g
Structural-coherence-≈Term-noσ {f = f} {g = g} nf ng _ = noσ-discharge nf ng

-- `Structural-coherence-≈Term-σ` and the dispatcher
-- `Structural-coherence-≈Term` were previously postulated / built on
-- top of that postulate here.  They are unreached by the critical
-- completeness path (which only uses the constructive
-- `Structural-coherence-≈Term-noσ`), and have been removed so this
-- module is fully postulate-free under `--safe`.

--------------------------------------------------------------------------------
-- Derived: lift `Structural-coherence-≈Term` through `bridge` and
-- `decode-roundtrip-rel` to the original `decode-rel`-shaped lemma.
--
-- The derivation is purely categorical (no further postulates): the
-- `bridge`-wrapping is a congruence with respect to `_≈Term_`, and
-- `decode-rel f ≈Term bridge f` for every `f` by `decode-roundtrip-rel`.

private
  open import Categories.Category using (Category)
  module FM = Category FreeMonoidal
  open FM.HomReasoning

  -- `bridge` is a congruence for `_≈Term_`.  Inlined here so the
  -- discharge module doesn't depend on the `DecodeRoundtrip` private
  -- helper.
  bridge-resp-≈Term
    : ∀ {A B} {f g : HomTerm A B}
    → f ≈Term g → bridge f ≈Term bridge g
  bridge-resp-≈Term f≈g = refl⟩∘⟨ f≈g ⟩∘⟨refl

-- `Structural-coherence` (the decode-rel-level lift of
-- `Structural-coherence-≈Term`) is unreached by the critical
-- completeness path and was removed along with the σ-postulate above.

--------------------------------------------------------------------------------
-- Discharge the original postulate.
--
-- `Atomic f` + `nE ⟪ f ⟫ ≡ 0` ⇒ `Structural f` (rules out `Agen`).
-- For the atomic shapes routed into the `…-0E` case from
-- `AtomicCompound.dispatch-structural`, the atomic-side edge count is
-- 0 by construction (see `nE-{id,λ⇒,λ⇐,ρ⇒,ρ⇐,α⇒,α⇐,σ}` there) — we
-- recover that here by case-splitting on the `Atomic` witness rather
-- than threading the edge-count proof through the API.

-- The originally-postulated lemma.  Note: the `Atomic f` hypothesis
-- combined with the dispatch from `AtomicCompound.dispatch-structural`
-- guarantees that `f` is *not* `Agen` (the Agen branch routes to
-- `decode-rel-resp-≅ᴴ-Agen-compound-1E` instead).  We extract a
-- `Structural f` witness by case-analysis on `Atomic f`, where the
-- `Agen` branch is dismissed via the iso witness's edge-count
-- transport (a `Fin 1 ↔ Fin 0` contradiction).

-- The discharge of `decode-rel-resp-≅ᴴ-atomic-compound-0E`.  Note we
-- *drop* the redundant `Compound g` hypothesis: under
-- `nE ⟪ g ⟫ ≡ 0`, the `Compound g` argument carries no information
-- beyond the boundary types, since `Structural g` is recovered from
-- the edge-count witness alone (see `nE-0→Structural`).  Dropping it
-- breaks an otherwise-circular import between `AtomicCompound.agda`
-- (which defines `Compound`) and this module.  The caller in
-- `AtomicCompound.agda` ignores the redundant argument when wiring up.

-- `decode-rel-resp-≅ᴴ-atomic-compound-0E` was the original entry
-- point through the dispatcher / σ-postulate.  Unreached by the
-- critical completeness path, removed along with the postulates above.
