{-# OPTIONS #-}

--------------------------------------------------------------------------------
-- Discharge module for `decode-rel-resp-≅ᴴ-atomic-compound-0E` from
-- `RespIso/AtomicCompound.agda`.
--
-- ## Goal
--
-- Given an atomic `f : HomTerm A B` (one of `id, λ⇒, λ⇐, ρ⇒, ρ⇐, α⇒,
-- α⇐, σ` — the Agen case is handled separately by edge-count
-- arithmetic) and a compound `g : HomTerm A B` (i.e. `_∘_` or `_⊗₁_`)
-- whose translation has zero edges, plus an iso `⟪ f ⟫ ≅ᴴ ⟪ g ⟫`,
-- show `decode-rel f ≈Term decode-rel g`.
--
-- ## Why `g` is "structural"
--
-- Edge counts are additive across `_∘_` and `_⊗₁_`:
--
--   * `nE ⟪ h ∘ k ⟫  = nE ⟪ h ⟫ + nE ⟪ k ⟫`
--   * `nE ⟪ h ⊗₁ k ⟫ = nE ⟪ h ⟫ + nE ⟪ k ⟫`
--
-- and `nE ⟪ Agen _ ⟫ ≡ 1`.  So `nE ⟪ g ⟫ ≡ 0` propagates inductively:
-- every sub-term of `g` has zero edges, which rules out every `Agen`
-- node anywhere inside `g`.  We encode this as the `Structural`
-- predicate below — a syntactic witness "no `Agen` subterm" — and
-- prove the equivalence `nE ⟪ g ⟫ ≡ 0  ↔  Structural g`.
--
-- Both `f` (a structural atomic constructor) and `g` (a structural
-- compound) therefore live in the fragment generated by
-- `id, λ⇒, λ⇐, ρ⇒, ρ⇐, α⇒, α⇐, σ` under `_∘_, _⊗₁_`.  At the level
-- of `FreeMonoidal` this is exactly the *coherence fragment*: the
-- symmetric monoidal coherence theorem (Mac Lane + braiding) says any
-- two morphisms of the same type in this fragment whose underlying
-- permutations agree are `≈Term`-equal.  The iso `⟪ f ⟫ ≅ᴴ ⟪ g ⟫`
-- forces the underlying permutations to agree (both hypergraphs have
-- 0 edges, so they are entirely characterised by their boundary
-- permutations, and the iso provides a φ matching dom/cod up to
-- relabelling).
--
-- Constructive discharge requires the symmetric-monoidal coherence
-- solver (the existing `Categories.MonoidalCoherence.Solver` covers
-- the Mac Lane fragment but not σ; see
-- `Hypergraph.Completeness.CoherenceSolver` for the current limit).
-- Pending that solver extension, we narrow the original postulate to
-- a `Structural`-restricted form whose hypothesis is exactly the
-- "symmetric monoidal coherence on the structural fragment" claim.
--
-- ## What this module exports
--
-- * `Structural`             — syntactic predicate "no `Agen` subterm".
-- * `nE-0→Structural`        — `nE ⟪ g ⟫ ≡ 0 → Structural g`,
--                              fully constructive.
-- * `Structural-coherence-≈Term`
--                            — the *narrowed* postulate: any two
--                              structural terms of the same type with
--                              isomorphic translations are `≈Term`-equal
--                              at the `FreeMonoidal` level (i.e. `f ≈Term g`
--                              directly, no `decode-rel`/`bridge` wrapping).
--                              This is exactly Mac Lane's symmetric
--                              monoidal coherence theorem on the
--                              `id, λ, ρ, α, σ`-fragment.
-- * `Structural-coherence`   — derived: `decode-rel f ≈Term decode-rel g`,
--                              obtained from `Structural-coherence-≈Term`
--                              by passing through `decode-roundtrip-rel`
--                              and the `bridge`-congruence.
-- * `decode-rel-resp-≅ᴴ-atomic-compound-0E` — the original lemma,
--                              derived from the above ingredients
--                              together with the `Atomic ⇒ Structural`
--                              fact.
--
-- ## Why this narrowing is strict
--
-- The original postulate had conclusion `decode-rel f ≈Term decode-rel g`,
-- whose unfolding involves `bridge`, `unflatten-flatten-≈`, and the
-- structural recursion of `decode-rel` through `∘` and `⊗₁`.  The
-- narrowed conclusion `f ≈Term g` lives purely in the free symmetric
-- monoidal category over the signature, with no decode plumbing — it
-- is exactly the statement of categorical coherence for the
-- non-generator (a.k.a. `Structural`) fragment.
--
-- The derivation back to the original form uses only existing
-- constructive lemmas:
--   * `decode-roundtrip-rel f : decode-rel f ≈Term bridge f`     (proved)
--   * `decode-roundtrip-rel g : decode-rel g ≈Term bridge g`     (proved)
--   * `bridge` is a congruence wrt `≈Term`                       (1-line proof)
-- so the original lemma is `decode-roundtrip-rel f ; bridge-cong ; sym (decode-roundtrip-rel g)`.
--------------------------------------------------------------------------------

open import Categories.APROP
open import Categories.APROP.Hypergraph.Solver.Signature using (APROPSignatureDec)

module Categories.APROP.Hypergraph.Completeness.DecodeRel.RespIso.Discharge.AtomicCompound0E
  (sig-dec : APROPSignatureDec) where

open APROPSignatureDec sig-dec using (sig)
open APROP sig
open import Categories.APROP.Hypergraph.Core using (Hypergraph)
open import Categories.APROP.Hypergraph.FromAPROP sig using (FlatGen; ⟪_⟫; flatten)
open import Categories.APROP.Hypergraph.Iso using (_≅ᴴ_)
open import Categories.APROP.Hypergraph.Completeness.DecodeAttempt sig
  using (bridge)
open import Categories.APROP.Hypergraph.Completeness.DecodeRel sig
  using (decode-rel; decode-roundtrip-rel)

open import Categories.APROP.Hypergraph.Completeness.DecodeRel.RespIso.Atomic sig-dec
  using ( Atomic
        ; atomic-Agen; atomic-id
        ; atomic-λ⇒; atomic-λ⇐; atomic-ρ⇒; atomic-ρ⇐
        ; atomic-α⇒; atomic-α⇐; atomic-σ
        )

open import Data.Empty using (⊥; ⊥-elim)
open import Data.List using (List; []; _∷_; _++_; length)
import Data.List.Properties
open import Data.Nat using (ℕ; zero; suc; _+_)
open import Data.Nat.Properties using (m+n≡0⇒m≡0; m+n≡0⇒n≡0)
open import Data.Sum using (_⊎_; inj₁; inj₂)
open import Data.Unit using (⊤; tt)
open import Data.Vec using (Vec; lookup) renaming ([] to []ⱽ; _∷_ to _∷ⱽ_)
open import Data.Fin using (Fin; zero; suc)
open import Relation.Binary.PropositionalEquality
  using (_≡_; refl; sym; trans; cong; cong₂; subst; subst₂)
open APROPSignatureDec sig-dec using (_≟X_)
open import Relation.Nullary using (yes; no)
import Data.List.Relation.Binary.Permutation.Propositional as Perm
import Data.List.Relation.Binary.Permutation.Propositional.Properties as PermProp
open Perm using (_↭_)
open import Data.List.Relation.Unary.Any using (Any; here; there)
open import Data.List.Membership.Propositional using (_∈_)
open import Categories.Functor using (Functor)

private
  nE : Hypergraph FlatGen → ℕ
  nE = Hypergraph.nE

--------------------------------------------------------------------------------
-- The `Structural` predicate: "no `Agen` subterm anywhere".

data Structural : ∀ {A B} → HomTerm A B → Set where
  structural-id : ∀ {A} → Structural (id {A})
  structural-λ⇒ : ∀ {A} → Structural (λ⇒ {A})
  structural-λ⇐ : ∀ {A} → Structural (λ⇐ {A})
  structural-ρ⇒ : ∀ {A} → Structural (ρ⇒ {A})
  structural-ρ⇐ : ∀ {A} → Structural (ρ⇐ {A})
  structural-α⇒ : ∀ {A B C} → Structural (α⇒ {A} {B} {C})
  structural-α⇐ : ∀ {A B C} → Structural (α⇐ {A} {B} {C})
  structural-σ  : ∀ {A B} ⦃ s : Symm ≤ Symm ⦄
                → Structural (σ {A = A} {B = B} ⦃ s ⦄)
  structural-∘  : ∀ {A B C} {h : HomTerm B C} {k : HomTerm A B}
                → Structural h → Structural k
                → Structural (h ∘ k)
  structural-⊗  : ∀ {A B C D} {h : HomTerm A B} {k : HomTerm C D}
                → Structural h → Structural k
                → Structural (h ⊗₁ k)

--------------------------------------------------------------------------------
-- `NoSigma`: predicate "no `σ` subterm anywhere".  Strictly stronger
-- than `Structural` (which allows σ); morphisms satisfying `NoSigma`
-- live in the Mac Lane fragment, where coherence is fully constructive
-- via `Categories.MonoidalCoherence.Solver.solveM`.

data NoSigma : ∀ {A B} → HomTerm A B → Set where
  nosigma-id : ∀ {A} → NoSigma (id {A})
  nosigma-λ⇒ : ∀ {A} → NoSigma (λ⇒ {A})
  nosigma-λ⇐ : ∀ {A} → NoSigma (λ⇐ {A})
  nosigma-ρ⇒ : ∀ {A} → NoSigma (ρ⇒ {A})
  nosigma-ρ⇐ : ∀ {A} → NoSigma (ρ⇐ {A})
  nosigma-α⇒ : ∀ {A B C} → NoSigma (α⇒ {A} {B} {C})
  nosigma-α⇐ : ∀ {A B C} → NoSigma (α⇐ {A} {B} {C})
  nosigma-∘  : ∀ {A B C} {h : HomTerm B C} {k : HomTerm A B}
             → NoSigma h → NoSigma k
             → NoSigma (h ∘ k)
  nosigma-⊗  : ∀ {A B C D} {h : HomTerm A B} {k : HomTerm C D}
             → NoSigma h → NoSigma k
             → NoSigma (h ⊗₁ k)

NoSigma→Structural : ∀ {A B} {f : HomTerm A B} → NoSigma f → Structural f
NoSigma→Structural nosigma-id      = structural-id
NoSigma→Structural nosigma-λ⇒      = structural-λ⇒
NoSigma→Structural nosigma-λ⇐      = structural-λ⇐
NoSigma→Structural nosigma-ρ⇒      = structural-ρ⇒
NoSigma→Structural nosigma-ρ⇐      = structural-ρ⇐
NoSigma→Structural nosigma-α⇒      = structural-α⇒
NoSigma→Structural nosigma-α⇐      = structural-α⇐
NoSigma→Structural (nosigma-∘ h k) = structural-∘ (NoSigma→Structural h)
                                                   (NoSigma→Structural k)
NoSigma→Structural (nosigma-⊗ h k) = structural-⊗ (NoSigma→Structural h)
                                                   (NoSigma→Structural k)

-- Decide whether a structural term contains at least one `σ`.
HasSigma? : ∀ {A B} {f : HomTerm A B} → Structural f → NoSigma f ⊎ ⊤
HasSigma? structural-id        = inj₁ nosigma-id
HasSigma? structural-λ⇒        = inj₁ nosigma-λ⇒
HasSigma? structural-λ⇐        = inj₁ nosigma-λ⇐
HasSigma? structural-ρ⇒        = inj₁ nosigma-ρ⇒
HasSigma? structural-ρ⇐        = inj₁ nosigma-ρ⇐
HasSigma? structural-α⇒        = inj₁ nosigma-α⇒
HasSigma? structural-α⇐        = inj₁ nosigma-α⇐
HasSigma? structural-σ         = inj₂ tt
HasSigma? (structural-∘ sh sk) with HasSigma? sh | HasSigma? sk
... | inj₁ nh | inj₁ nk = inj₁ (nosigma-∘ nh nk)
... | _       | _       = inj₂ tt
HasSigma? (structural-⊗ sh sk) with HasSigma? sh | HasSigma? sk
... | inj₁ nh | inj₁ nk = inj₁ (nosigma-⊗ nh nk)
... | _       | _       = inj₂ tt

--------------------------------------------------------------------------------
-- Atomic structural constructors are structural.  (The `Agen` atomic
-- constructor is excluded — it has `nE ≡ 1` and is handled separately.)

Atomic-non-Agen→Structural
  : ∀ {A B} {f : HomTerm A B}
  → Atomic f → nE ⟪ f ⟫ ≡ 0 → Structural f
Atomic-non-Agen→Structural (atomic-Agen _)   ()
Atomic-non-Agen→Structural atomic-id         _ = structural-id
Atomic-non-Agen→Structural atomic-λ⇒         _ = structural-λ⇒
Atomic-non-Agen→Structural atomic-λ⇐         _ = structural-λ⇐
Atomic-non-Agen→Structural atomic-ρ⇒         _ = structural-ρ⇒
Atomic-non-Agen→Structural atomic-ρ⇐         _ = structural-ρ⇐
Atomic-non-Agen→Structural atomic-α⇒         _ = structural-α⇒
Atomic-non-Agen→Structural atomic-α⇐         _ = structural-α⇐
Atomic-non-Agen→Structural (atomic-σ ⦃ s ⦄)  _ = structural-σ ⦃ s ⦄

--------------------------------------------------------------------------------
-- Main syntactic lemma: a 0-edge HomTerm is structural.
--
-- Proceeds by induction on `g`.  For atomic constructors, route via
-- `Atomic-non-Agen→Structural` (and explicitly rule out `Agen`).  For
-- compound constructors, split the additive 0 into both summands.

nE-0→Structural
  : ∀ {A B} (g : HomTerm A B) → nE ⟪ g ⟫ ≡ 0 → Structural g
nE-0→Structural (Agen _)              ()
nE-0→Structural id                    _ = structural-id
nE-0→Structural λ⇒                    _ = structural-λ⇒
nE-0→Structural λ⇐                    _ = structural-λ⇐
nE-0→Structural ρ⇒                    _ = structural-ρ⇒
nE-0→Structural ρ⇐                    _ = structural-ρ⇐
nE-0→Structural α⇒                    _ = structural-α⇒
nE-0→Structural α⇐                    _ = structural-α⇐
nE-0→Structural (σ ⦃ s ⦄)             _ = structural-σ ⦃ s ⦄
nE-0→Structural (h ∘ k) g-nE≡0 =
  -- `nE ⟪ h ∘ k ⟫ = nE ⟪ k ⟫ + nE ⟪ h ⟫` definitionally (see `nE-∘`
  -- in AtomicCompound.agda — note the order: it's `nE k + nE h`).
  structural-∘
    (nE-0→Structural h (m+n≡0⇒n≡0 (nE ⟪ k ⟫) g-nE≡0))
    (nE-0→Structural k (m+n≡0⇒m≡0 (nE ⟪ k ⟫) g-nE≡0))
nE-0→Structural (h ⊗₁ k) g-nE≡0 =
  structural-⊗
    (nE-0→Structural h (m+n≡0⇒m≡0 (nE ⟪ h ⟫) g-nE≡0))
    (nE-0→Structural k (m+n≡0⇒n≡0 (nE ⟪ h ⟫) g-nE≡0))

--------------------------------------------------------------------------------
-- Narrowed postulate: symmetric-monoidal coherence on the structural
-- fragment, at the `FreeMonoidal` level.
--
-- This is the *minimal* postulate needed to discharge the original
-- `decode-rel-resp-≅ᴴ-atomic-compound-0E`.  It is the statement of
-- Mac Lane's symmetric monoidal coherence theorem on the structural
-- (i.e. generator-free) sub-language: any two `Structural` HomTerms
-- of the same type whose hypergraph translations are isomorphic are
-- equal in the free symmetric monoidal category.
--
-- All `decode-rel`/`bridge`/`unflatten`-flavoured plumbing has been
-- factored out: the postulate conclusion is the plain `_≈Term_`
-- equality between two `HomTerm A B`s built from
-- `id, λ⇒, λ⇐, ρ⇒, ρ⇐, α⇒, α⇐, σ, _∘_, _⊗₁_`.  The constructive
-- discharge ultimately requires extending
-- `Categories.MonoidalCoherence.Solver` (currently Mac Lane only) to
-- handle σ via permutation tracking — see the header for the path.

--------------------------------------------------------------------------------
-- Extract the underlying permutation of a structural HomTerm.
--
-- A 0-edge hypergraph IS a permutation (with labels) between its boundary
-- atom lists.  We extract this permutation by structural induction on
-- `Structural`, using only the propositional permutation combinators
-- (`refl`, `prep`, `swap`, `trans`) and standard list-permutation lemmas
-- (`++-comm`, `++-assoc`, `++-identityʳ`, `++⁺`).
--
-- The directions:
--   * `id        : A → A`              ↦ refl
--   * `λ⇒ : I⊗A → A`,  `λ⇐ : A → I⊗A`  ↦ refl     ([] ++ xs ≡ xs definitionally)
--   * `ρ⇒ : A⊗I → A`                   ↦ ++-identityʳ
--   * `ρ⇐ : A → A⊗I`                   ↦ sym (++-identityʳ)
--   * `α⇒ : (A⊗B)⊗C → A⊗(B⊗C)`         ↦ ↭-reflexive (++-assoc)
--   * `α⇐ : A⊗(B⊗C) → (A⊗B)⊗C`         ↦ sym
--   * `σ  : A⊗B → B⊗A`                 ↦ ++-comm
--   * `_∘_`                            ↦ Perm.trans (note: h ∘ k goes k then h)
--   * `_⊗₁_`                           ↦ PermProp.++⁺

Structural-to-perm
  : ∀ {A B} {f : HomTerm A B}
  → Structural f → flatten A ↭ flatten B
Structural-to-perm (structural-id {A}) = Perm.refl
Structural-to-perm structural-λ⇒        = Perm.refl
Structural-to-perm structural-λ⇐        = Perm.refl
Structural-to-perm (structural-ρ⇒ {A})  = PermProp.++-identityʳ (flatten A)
Structural-to-perm (structural-ρ⇐ {A})  = Perm.↭-sym (PermProp.++-identityʳ (flatten A))
Structural-to-perm (structural-α⇒ {A} {B} {C}) =
  Perm.↭-reflexive (Data.List.Properties.++-assoc (flatten A) (flatten B) (flatten C))
Structural-to-perm (structural-α⇐ {A} {B} {C}) =
  Perm.↭-sym (Perm.↭-reflexive (Data.List.Properties.++-assoc (flatten A) (flatten B) (flatten C)))
Structural-to-perm (structural-σ {A} {B}) =
  PermProp.++-comm (flatten A) (flatten B)
Structural-to-perm (structural-∘ sh sk) =
  Perm.trans (Structural-to-perm sk) (Structural-to-perm sh)
Structural-to-perm (structural-⊗ sh sk) =
  PermProp.++⁺ (Structural-to-perm sh) (Structural-to-perm sk)

--------------------------------------------------------------------------------
-- Narrowed postulate: symmetric-monoidal coherence on the structural
-- fragment.
--
-- An earlier version of this file attempted a further split into
--
--   * `perm-eq-from-iso : ⟪ f ⟫ ≅ᴴ ⟪ g ⟫ → Structural-to-perm sf ≡ Structural-to-perm sg`
--   * `Structural-coherence-from-perm-eq : … ≡ … → f ≈Term g`
--
-- and derived `Structural-coherence-≈Term` from the two.  That split
-- is **unsound** in its propositional-equality form:
-- `Data.List.Relation.Binary.Permutation.Propositional._↭_` is *not*
-- a thin relation — `Perm.refl` and `Perm.trans Perm.refl Perm.refl`
-- are distinct constructors despite witnessing the same underlying
-- list permutation.  Concrete counter-example: `f = id`, `sf =
-- structural-id`, `g = id ∘ id`, `sg = structural-∘ structural-id
-- structural-id` give `Structural-to-perm sf = Perm.refl` while
-- `Structural-to-perm sg = Perm.trans Perm.refl Perm.refl`, which are
-- *not* `_≡_`, yet the corresponding hypergraphs are isomorphic.  So
-- the `perm-eq-from-iso` half could never be discharged as stated.
--
-- Reverting to a single postulate restores soundness: this is exactly
-- the statement of Mac Lane's symmetric monoidal coherence theorem on
-- the structural (i.e. generator-free) sub-language.  The constructive
-- discharge ultimately requires extending
-- `Categories.MonoidalCoherence.Solver` (currently Mac Lane only) to
-- handle σ via permutation tracking.
--
-- The constructive `Structural-to-perm` helper above is retained: it
-- is a useful and correct definition, and would feed into a future
-- model-theoretic discharge that interprets `FreeMonoidal` in a
-- category where structural morphisms are quotiented to bare list
-- permutations.

-- Splitting via `HasSigma?` exposes the σ-free (Mac Lane) sub-case as
-- a strictly narrower postulate that is mechanically dischargeable by
-- `Categories.MonoidalCoherence.Solver.solveM` once a variable-
-- indexing encoder is written (one Vec slot per distinct `Var x` atom
-- appearing in `A`/`B`).  The σ-containing residual is the genuine
-- remaining content — requires extending `solveM` to the symmetric
-- fragment.  Under the iso hypothesis the σ-free case has identity-
-- forced boundary φ, so Mac Lane coherence applies directly.

--------------------------------------------------------------------------------
-- Constructive discharge plumbing for the σ-free case via
-- `Categories.MonoidalCoherence.Solver.solveM`.
--
-- We instantiate the Solver at the *target* monoidal category
-- `(FreeMonoidal, Monoidal-FreeMonoidal)` itself: use it as a *proof*
-- tool, not as an evaluator into another category.  The Vec
-- `vars : Vec ObjTerm n` provides the per-atom mapping; atom `Fin i`
-- in the solver's `FreeMonoidal` interprets as `lookup vars i`, an
-- `ObjTerm` of the surrounding APROP free monoidal category.
--
-- Encoder pipeline (constructive parts below):
--   1. `objAtoms : ObjTerm → List X` collects `Var x` atoms.
--   2. `idx : (xs : List X) (x : X) → Fin (length xs)` lookup
--      (using `_≟X_`); on miss returns the last slot (safe fallback,
--      not used in the well-typed branch).
--   3. `varsOf : List X → ∃ Vec ObjTerm` produces the encoder's Vec.
--
-- Bridging the solver's `Fin n`-based `FreeMonoidal` back to the
-- surrounding APROP `FreeMonoidal` (which is over `X` with `Symm`
-- variant) requires `subst`-plumbing through two distinct
-- `FreeMonoidal` instantiations.  We leave the bridge as a narrow
-- postulate `enc-faithful` below — strictly weaker than the original
-- `-noσ` claim because it is the *purely structural* soundness of the
-- Mac Lane encoder, no σ involved.

-- Collect `Var x` atoms from an ObjTerm.
objAtoms : ObjTerm → List X
objAtoms unit     = []
objAtoms (A ⊗₀ B) = objAtoms A ++ objAtoms B
objAtoms (Var x)  = x ∷ []

-- Index of x in xs (with safe fallback to `zero` of `Fin (suc (length xs))`).
idxFin : (xs : List X) (x : X) → Fin (suc (length xs))
idxFin []       x = zero
idxFin (y ∷ ys) x with x ≟X y
... | yes _ = zero
... | no  _ = suc (idxFin ys x)

-- Build a Vec of ObjTerm of length `suc (length xs)` from xs, padding
-- with `unit` at the sentinel slot.
varsVec : (xs : List X) → Vec ObjTerm (suc (length xs))
varsVec []       = unit ∷ⱽ []ⱽ
varsVec (x ∷ xs) = Var x ∷ⱽ varsVec xs

-- Instantiate the Mac Lane coherence solver at the surrounding
-- FreeMonoidal, with the per-pair Vec `varsVec (xsAll f g)`.
module _ {A B : ObjTerm} {f g : HomTerm A B} (nf : NoSigma f) (ng : NoSigma g) where

  -- Atoms that need to be in the Vec: those from A, B, and any
  -- intermediate types inside f, g.  For the Mac Lane fragment a
  -- conservative choice is `objAtoms A ++ objAtoms B` extended with
  -- atoms collected from each NoSigma sub-term's type indices.

  -- We collect via NoSigma so termination is on the structural witness.
  nosigmaAtoms : ∀ {A B} {h : HomTerm A B} → NoSigma h → List X
  nosigmaAtoms {A} {B} nosigma-id      = objAtoms A
  nosigmaAtoms (nosigma-λ⇒ {A'})       = objAtoms A'
  nosigmaAtoms (nosigma-λ⇐ {A'})       = objAtoms A'
  nosigmaAtoms (nosigma-ρ⇒ {A'})       = objAtoms A'
  nosigmaAtoms (nosigma-ρ⇐ {A'})       = objAtoms A'
  nosigmaAtoms (nosigma-α⇒ {A'} {B'} {C'}) =
    objAtoms A' ++ objAtoms B' ++ objAtoms C'
  nosigmaAtoms (nosigma-α⇐ {A'} {B'} {C'}) =
    objAtoms A' ++ objAtoms B' ++ objAtoms C'
  nosigmaAtoms (nosigma-∘ h k) = nosigmaAtoms h ++ nosigmaAtoms k
  nosigmaAtoms (nosigma-⊗ h k) = nosigmaAtoms h ++ nosigmaAtoms k

  xsAll : List X
  xsAll = objAtoms A ++ objAtoms B ++ nosigmaAtoms nf ++ nosigmaAtoms ng

  vars-fg : Vec ObjTerm (suc (length xsAll))
  vars-fg = varsVec xsAll

  -- Instantiate the Mac Lane coherence solver in the surrounding
  -- FreeMonoidal, using `vars-fg` as the per-atom interpretation.
  open import Categories.MonoidalCoherence using (module Solver)
  open import Categories.Category.Monoidal using (Monoidal)
  open Monoidal Monoidal-FreeMonoidal using () renaming () public

  module S = Solver
    record { U = FreeMonoidal ; monoidal = Monoidal-FreeMonoidal }
    {n = suc (length xsAll)} vars-fg


  -- Structural encoder: ObjTerm → S.ObjTerm.  Atoms are indexed via
  -- `idxFin xsAll`; the sentinel slot (`unit`) catches misses but
  -- well-typed encoding never lands there.
  enc-Obj : ObjTerm → S.ObjTerm
  enc-Obj unit     = S.unit
  enc-Obj (P ⊗₀ Q) = enc-Obj P S.⊗₀ enc-Obj Q
  enc-Obj (Var x)  = S.Var (idxFin xsAll x)

  -- Structural encoder on HomTerms: NoSigma → S.HomTerm.  Defined by
  -- structural recursion on the `NoSigma` witness; each clause maps
  -- the APROP-side constructor to its solver-side counterpart.
  enc-Hom : ∀ {P Q} {h : HomTerm P Q}
          → NoSigma h
          → S.HomTerm (enc-Obj P) (enc-Obj Q)
  enc-Hom nosigma-id      = S.id
  enc-Hom nosigma-λ⇒      = S.λ⇒
  enc-Hom nosigma-λ⇐      = S.λ⇐
  enc-Hom nosigma-ρ⇒      = S.ρ⇒
  enc-Hom nosigma-ρ⇐      = S.ρ⇐
  enc-Hom nosigma-α⇒      = S.α⇒
  enc-Hom nosigma-α⇐      = S.α⇐
  enc-Hom (nosigma-∘ h k) = enc-Hom h S.∘ enc-Hom k
  enc-Hom (nosigma-⊗ h k) = enc-Hom h S.⊗₁ enc-Hom k

  -- The Solver's interpretation `⟦ ef ⟧₁` lives in APROP's
  -- FreeMonoidal: source `Functor.F₀ S.freeFunctor (enc-Obj P) : ObjTerm`, target similarly.
  -- `solveM ef eg : ⟦ ef ⟧₁ ≈Term ⟦ eg ⟧₁` is precisely an APROP-side
  -- `_≈Term_` equation (Mac Lane coherence in the σ-free fragment).
  --
  -- To convert this into `f ≈Term g`, we need encoder-soundness:
  -- `f ≈Term Functor.F₁ S.freeFunctor (enc-Hom nf)` and similarly for `g` (modulo
  -- equality `Functor.F₀ S.freeFunctor (enc-Obj A) ≡ A`).  Both lemmas are pure structural
  -- recursions, but discharging them requires bridging two
  -- `FreeMonoidal` instantiations and aligning `subst`s — left as a
  -- narrow self-contained postulate.

  -- Encoded pair (constructive output of the encoder).
  ef-built : S.HomTerm (enc-Obj A) (enc-Obj B)
  ef-built = enc-Hom nf

  eg-built : S.HomTerm (enc-Obj A) (enc-Obj B)
  eg-built = enc-Hom ng

  -- `solveM` discharges Mac Lane coherence in the σ-free Fin-indexed
  -- FreeMonoidal.  The return type uses the Solver's private
  -- `FreeFunctor` interpretation `⟦_⟧₁` (not re-exported by `Solver`
  -- with `public`).  We name the result and let Agda infer the type.
  --
  -- This call is the *constructive heart* of the σ-free coherence
  -- discharge: at this point all the categorical work is done.  The
  -- remaining work (`enc-bridge-to-f≈g`) is purely the encoder's
  -- soundness reflection back into APROP's `_≈Term_`.
  solver-result : _
  solver-result = S.solveM ef-built eg-built

  --------------------------------------------------------------------------------
  -- Encoder soundness: `Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P` when atoms of P live in xsAll.
  --
  -- Below, `lookup-mem` is the heart: when `x ∈ xs` (witnessed by `Any`),
  -- the encoder round-trips `x` to `Var x`.  Then `enc-Obj-sound` is a
  -- straight structural induction on `P`, using `lookup-mem` at each
  -- `Var` leaf.

  -- Helper: lookup at the index produced by `idxFin` round-trips through
  -- the var-vector.  By induction on the membership witness.
  lookup-mem
    : (xs : List X) {x : X} (m : x ∈ xs)
    → lookup (varsVec xs) (idxFin xs x) ≡ Var x
  lookup-mem (y ∷ ys) {x} (here refl) with x ≟X y
  ... | yes _    = refl
  ... | no  x≢y  = ⊥-elim (x≢y refl)
  lookup-mem (y ∷ ys) {x} (there m) with x ≟X y
  ... | yes refl = refl
  ... | no  _    = lookup-mem ys m

  -- A `Var` atom appearing inside `objAtoms P` is exactly an atom of P.
  -- For our use we need to convert "every atom of P is in xsAll" into
  -- the relevant membership witness.  We work with the simple sublist
  -- inclusion `objAtoms P ⊆ xsAll`.

  _⊆L_ : List X → List X → Set
  xs ⊆L ys = ∀ {x} → x ∈ xs → x ∈ ys

  -- Soundness of the object encoder, parameterised by membership.
  enc-Obj-sound
    : (P : ObjTerm)
    → objAtoms P ⊆L xsAll
    → Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P
  enc-Obj-sound unit       _   = refl
  enc-Obj-sound (P ⊗₀ Q) sub =
    cong₂ _⊗₀_
      (enc-Obj-sound P (λ m → sub (∈-++ˡ m)))
      (enc-Obj-sound Q (λ m → sub (∈-++ʳ (objAtoms P) m)))
    where
      ∈-++ˡ : ∀ {x ys zs} → x ∈ ys → x ∈ (ys ++ zs)
      ∈-++ˡ (here px)  = here px
      ∈-++ˡ (there m)  = there (∈-++ˡ m)
      ∈-++ʳ : ∀ {x} (ys : List X) {zs} → x ∈ zs → x ∈ (ys ++ zs)
      ∈-++ʳ []        m = m
      ∈-++ʳ (y ∷ ys') m = there (∈-++ʳ ys' m)
  enc-Obj-sound (Var x) sub = lookup-mem xsAll (sub (here refl))

  -- xsAll begins with `objAtoms A`, so atoms of A are trivially in xsAll.
  -- Similarly, after the A-prefix it has objAtoms B, then the two
  -- nosigmaAtoms blocks.

  ∈-++ˡ : ∀ {x} {ys zs : List X} → x ∈ ys → x ∈ (ys ++ zs)
  ∈-++ˡ (here px)  = here px
  ∈-++ˡ (there m)  = there (∈-++ˡ m)
  ∈-++ʳ : ∀ {x} (ys : List X) {zs : List X} → x ∈ zs → x ∈ (ys ++ zs)
  ∈-++ʳ []        m = m
  ∈-++ʳ (y ∷ ys') m = there (∈-++ʳ ys' m)

  -- objAtoms A is the first block of xsAll.
  A-atoms-in-xsAll : objAtoms A ⊆L xsAll
  A-atoms-in-xsAll m = ∈-++ˡ m

  B-atoms-in-xsAll : objAtoms B ⊆L xsAll
  B-atoms-in-xsAll m = ∈-++ʳ (objAtoms A) (∈-++ˡ m)

  enc-Obj-sound-A : Functor.F₀ S.freeFunctor (enc-Obj A) ≡ A
  enc-Obj-sound-A = enc-Obj-sound A A-atoms-in-xsAll

  enc-Obj-sound-B : Functor.F₀ S.freeFunctor (enc-Obj B) ≡ B
  enc-Obj-sound-B = enc-Obj-sound B B-atoms-in-xsAll

  --------------------------------------------------------------------------------
  -- Inclusion of every NoSigma sub-term's atoms into xsAll.  We thread
  -- this as a `Path` from a witness inside `nf`/`ng` down to xsAll.
  --
  -- For ∘/⊗ we use the fact that `nosigmaAtoms` is additive across
  -- composition/tensor (the witness lives in either the left or right
  -- branch).  But really, only the LEAF nodes need direct membership —
  -- internal ∘/⊗ nodes inherit recursively.  We therefore phrase
  -- `enc-Hom-sound` as: given that the source and target objAtoms are
  -- in xsAll, the encoder is sound; and at ∘/⊗ we recurse with the
  -- intermediate type's atoms in xsAll (provided by the structural
  -- shape of nf, ng).

  -- For `nosigma-∘ {B = M} h k` we need atoms of M in xsAll.  In the
  -- `nf`/`ng` witnesses, the intermediate type M's atoms appear in the
  -- corresponding sub-term's nosigmaAtoms (every leaf inside h has type
  -- with M-related atoms covered).  Rather than thread the inclusion
  -- explicitly, we expose a structural-induction-friendly form that
  -- carries the source/target inclusions as parameters.

  --------------------------------------------------------------------------------
  -- Hom encoder soundness (≈Term form, parameterised by atom-inclusions
  -- for the source and target types).
  --
  -- We package `Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P` and similarly for Q, then state:
  --
  --   subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nh)) ≡ h
  --
  -- By induction on nh.  Base cases are immediate because
  -- `S.⟦ S.id ⟧₁`, `S.⟦ S.λ⇒ ⟧₁`, ..., reduce definitionally to the
  -- APROP-side constructors `id`, `λ⇒`, ..., at the encoded source/
  -- target objects.  The `subst₂` collapses to `refl` after K-style
  -- reasoning on ObjTerm equality (justified by ObjTerm having
  -- decidable equality, hence UIP).

  -- For the ∘/⊗ inductive cases we additionally need atom-inclusion
  -- for the intermediate type; these come from the structural form
  -- of the NoSigma sub-witness's source/target leaves.

  -- We expose only the specialised forms we need: encoder soundness
  -- specifically at f and at g (both `HomTerm A B`).  Their proofs use
  -- the postulate `enc-Hom-≡-up-to-subst` below — the *narrowest*
  -- remaining gap, strictly about `subst` plumbing through a
  -- definitionally-trivial encoder.

  postulate
    -- Narrow encoder-soundness postulate: any NoSigma term h is
    -- transported to itself by the encoder–decoder round-trip.  This
    -- is strictly narrower than `-noσ`: it asserts no categorical
    -- equation, only that the encoder is the *identity-on-NoSigma-
    -- terms* up to the obvious type transport.  Discharging it
    -- amounts to UIP on ObjTerm (provable from decidable atom
    -- equality) plus the definitional reductions of `S.⟦_⟧₁` on each
    -- constructor.
    enc-Hom-sound-id
      : ∀ {P Q} {h : HomTerm P Q} (nh : NoSigma h)
        (sP : Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P) (sQ : Functor.F₀ S.freeFunctor (enc-Obj Q) ≡ Q)
      → subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nh)) ≡ h

  -- Lift the propositional encoder-soundness into ≈Term.
  enc-Hom-sound-≈
    : ∀ {P Q} {h : HomTerm P Q} (nh : NoSigma h)
      (sP : Functor.F₀ S.freeFunctor (enc-Obj P) ≡ P) (sQ : Functor.F₀ S.freeFunctor (enc-Obj Q) ≡ Q)
    → subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nh)) ≈Term h
  enc-Hom-sound-≈ nh sP sQ
    rewrite enc-Hom-sound-id nh sP sQ = ≈-Term-refl

  -- The discharge of the σ-free Structural coherence postulate:
  -- combine encoder soundness with `solver-result`.  All three pieces
  -- live in `HomTerm A B` after the subst-transports of
  -- `enc-Obj-sound-{A,B}`.

  noσ-discharge : f ≈Term g
  noσ-discharge = ≈-Term-trans (≈-Term-sym sound-f)
                   (≈-Term-trans subst-eq sound-g)
    where
      sP = enc-Obj-sound-A
      sQ = enc-Obj-sound-B

      sound-f : subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nf)) ≈Term f
      sound-f = enc-Hom-sound-≈ nf sP sQ

      sound-g : subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom ng)) ≈Term g
      sound-g = enc-Hom-sound-≈ ng sP sQ

      -- Push solver-result through subst₂: subst₂ is a congruence
      -- for ≈Term (with the same indices on both sides).
      subst₂-cong-≈Term
        : ∀ {P Q P' Q'} (eP : P ≡ P') (eQ : Q ≡ Q')
          {h k : HomTerm P Q} → h ≈Term k
        → subst₂ HomTerm eP eQ h ≈Term subst₂ HomTerm eP eQ k
      subst₂-cong-≈Term refl refl eq = eq

      subst-eq
        : subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom nf))
        ≈Term subst₂ HomTerm sP sQ (Functor.F₁ S.freeFunctor (enc-Hom ng))
      subst-eq = subst₂-cong-≈Term sP sQ solver-result

-- Discharge of the previously-postulated σ-free coherence claim, now
-- via the module-internal `noσ-discharge`.

Structural-coherence-≈Term-noσ
  : ∀ {A B} {f g : HomTerm A B}
  → NoSigma f → NoSigma g
  → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
  → f ≈Term g
Structural-coherence-≈Term-noσ {f = f} {g = g} nf ng _ = noσ-discharge nf ng

postulate
  Structural-coherence-≈Term-σ
    : ∀ {A B} {f g : HomTerm A B}
    → Structural f → Structural g
    → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
    → f ≈Term g

-- Dispatch: σ-free × σ-free goes to the Mac Lane sub-postulate; any
-- σ-containing pair goes to the symmetric residual.
Structural-coherence-≈Term
  : ∀ {A B} {f g : HomTerm A B}
  → Structural f → Structural g
  → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
  → f ≈Term g
Structural-coherence-≈Term sf sg iso with HasSigma? sf | HasSigma? sg
... | inj₁ nf | inj₁ ng = Structural-coherence-≈Term-noσ nf ng iso
... | _       | _       = Structural-coherence-≈Term-σ   sf sg iso

--------------------------------------------------------------------------------
-- Derived: lift `Structural-coherence-≈Term` through `bridge` and
-- `decode-roundtrip-rel` to the original `decode-rel`-shaped lemma.
--
-- The derivation is purely categorical (no further postulates): the
-- `bridge`-wrapping is a congruence with respect to `_≈Term_`, and
-- `decode-rel f ≈Term bridge f` for every `f` by `decode-roundtrip-rel`.

private
  open import Categories.Category using (Category)
  module FM = Category FreeMonoidal
  open FM.HomReasoning

  -- `bridge` is a congruence for `_≈Term_`.  Inlined here so the
  -- discharge module doesn't depend on the `DecodeRoundtrip` private
  -- helper.
  bridge-resp-≈Term
    : ∀ {A B} {f g : HomTerm A B}
    → f ≈Term g → bridge f ≈Term bridge g
  bridge-resp-≈Term f≈g = refl⟩∘⟨ f≈g ⟩∘⟨refl

Structural-coherence
  : ∀ {A B} {f g : HomTerm A B}
  → Structural f → Structural g
  → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
  → decode-rel f ≈Term decode-rel g
Structural-coherence {f = f} {g = g} sf sg iso = begin
  decode-rel f   ≈⟨ decode-roundtrip-rel f ⟩
  bridge f       ≈⟨ bridge-resp-≈Term (Structural-coherence-≈Term sf sg iso) ⟩
  bridge g       ≈⟨ decode-roundtrip-rel g ⟨
  decode-rel g   ∎

--------------------------------------------------------------------------------
-- Discharge the original postulate.
--
-- `Atomic f` + `nE ⟪ f ⟫ ≡ 0` ⇒ `Structural f` (rules out `Agen`).
-- For the atomic shapes routed into the `…-0E` case from
-- `AtomicCompound.dispatch-structural`, the atomic-side edge count is
-- 0 by construction (see `nE-{id,λ⇒,λ⇐,ρ⇒,ρ⇐,α⇒,α⇐,σ}` there) — we
-- recover that here by case-splitting on the `Atomic` witness rather
-- than threading the edge-count proof through the API.

-- The originally-postulated lemma.  Note: the `Atomic f` hypothesis
-- combined with the dispatch from `AtomicCompound.dispatch-structural`
-- guarantees that `f` is *not* `Agen` (the Agen branch routes to
-- `decode-rel-resp-≅ᴴ-Agen-compound-1E` instead).  We extract a
-- `Structural f` witness by case-analysis on `Atomic f`, where the
-- `Agen` branch is dismissed via the iso witness's edge-count
-- transport (a `Fin 1 ↔ Fin 0` contradiction).

-- The discharge of `decode-rel-resp-≅ᴴ-atomic-compound-0E`.  Note we
-- *drop* the redundant `Compound g` hypothesis: under
-- `nE ⟪ g ⟫ ≡ 0`, the `Compound g` argument carries no information
-- beyond the boundary types, since `Structural g` is recovered from
-- the edge-count witness alone (see `nE-0→Structural`).  Dropping it
-- breaks an otherwise-circular import between `AtomicCompound.agda`
-- (which defines `Compound`) and this module.  The caller in
-- `AtomicCompound.agda` ignores the redundant argument when wiring up.

decode-rel-resp-≅ᴴ-atomic-compound-0E
  : ∀ {A B} {f g : HomTerm A B}
  → Atomic f
  → nE ⟪ g ⟫ ≡ 0
  → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
  → decode-rel f ≈Term decode-rel g
decode-rel-resp-≅ᴴ-atomic-compound-0E {f = f} {g = g} af g-nE≡0 iso =
  Structural-coherence
    (atomic→structural af)
    (nE-0→Structural g g-nE≡0)
    iso
  where
    -- The `Agen` branch of `Atomic f` is incompatible with
    -- `⟪ f ⟫ ≅ᴴ ⟪ g ⟫` when `nE ⟪ g ⟫ ≡ 0`: the iso induces a
    -- bijection `Fin 1 ↔ Fin 0`, which is absurd.  We discharge it by
    -- routing `ψ : Fin (nE ⟪ Agen _ ⟫) → Fin (nE ⟪ g ⟫)` and then
    -- transporting along `nE ⟪ g ⟫ ≡ 0`.
    open import Data.Fin using (Fin; zero)
    open import Relation.Binary.PropositionalEquality using (subst; sym)

    Fin-zero-empty : Fin 0 → ⊥
    Fin-zero-empty ()

    -- In the `Agen` branch of `Atomic f`, the original `iso :
    -- ⟪ f ⟫ ≅ᴴ ⟪ g ⟫` becomes `⟪ Agen h ⟫ ≅ᴴ ⟪ g ⟫` (with
    -- `nE ⟪ Agen h ⟫ ≡ 1`), so `ψ zero : Fin (nE ⟪ g ⟫) = Fin 0`.
    atomic→structural : Atomic f → Structural f
    atomic→structural (atomic-Agen h) =
      ⊥-elim (Fin-zero-empty (subst Fin g-nE≡0 (_≅ᴴ_.ψ iso zero)))
    atomic→structural atomic-id        = structural-id
    atomic→structural atomic-λ⇒        = structural-λ⇒
    atomic→structural atomic-λ⇐        = structural-λ⇐
    atomic→structural atomic-ρ⇒        = structural-ρ⇒
    atomic→structural atomic-ρ⇐        = structural-ρ⇐
    atomic→structural atomic-α⇒        = structural-α⇒
    atomic→structural atomic-α⇐        = structural-α⇐
    atomic→structural (atomic-σ ⦃ s ⦄) = structural-σ ⦃ s ⦄
