{-# OPTIONS #-}

--------------------------------------------------------------------------------
-- Discharge module for `decode-rel-resp-≅ᴴ-atomic-compound-0E` from
-- `RespIso/AtomicCompound.agda`.
--
-- ## Goal
--
-- Given an atomic `f : HomTerm A B` (one of `id, λ⇒, λ⇐, ρ⇒, ρ⇐, α⇒,
-- α⇐, σ` — the Agen case is handled separately by edge-count
-- arithmetic) and a compound `g : HomTerm A B` (i.e. `_∘_` or `_⊗₁_`)
-- whose translation has zero edges, plus an iso `⟪ f ⟫ ≅ᴴ ⟪ g ⟫`,
-- show `decode-rel f ≈Term decode-rel g`.
--
-- ## Why `g` is "structural"
--
-- Edge counts are additive across `_∘_` and `_⊗₁_`:
--
--   * `nE ⟪ h ∘ k ⟫  = nE ⟪ h ⟫ + nE ⟪ k ⟫`
--   * `nE ⟪ h ⊗₁ k ⟫ = nE ⟪ h ⟫ + nE ⟪ k ⟫`
--
-- and `nE ⟪ Agen _ ⟫ ≡ 1`.  So `nE ⟪ g ⟫ ≡ 0` propagates inductively:
-- every sub-term of `g` has zero edges, which rules out every `Agen`
-- node anywhere inside `g`.  We encode this as the `Structural`
-- predicate below — a syntactic witness "no `Agen` subterm" — and
-- prove the equivalence `nE ⟪ g ⟫ ≡ 0  ↔  Structural g`.
--
-- Both `f` (a structural atomic constructor) and `g` (a structural
-- compound) therefore live in the fragment generated by
-- `id, λ⇒, λ⇐, ρ⇒, ρ⇐, α⇒, α⇐, σ` under `_∘_, _⊗₁_`.  At the level
-- of `FreeMonoidal` this is exactly the *coherence fragment*: the
-- symmetric monoidal coherence theorem (Mac Lane + braiding) says any
-- two morphisms of the same type in this fragment whose underlying
-- permutations agree are `≈Term`-equal.  The iso `⟪ f ⟫ ≅ᴴ ⟪ g ⟫`
-- forces the underlying permutations to agree (both hypergraphs have
-- 0 edges, so they are entirely characterised by their boundary
-- permutations, and the iso provides a φ matching dom/cod up to
-- relabelling).
--
-- Constructive discharge requires the symmetric-monoidal coherence
-- solver (the existing `Categories.MonoidalCoherence.Solver` covers
-- the Mac Lane fragment but not σ; see
-- `Hypergraph.Completeness.CoherenceSolver` for the current limit).
-- Pending that solver extension, we narrow the original postulate to
-- a `Structural`-restricted form whose hypothesis is exactly the
-- "symmetric monoidal coherence on the structural fragment" claim.
--
-- ## What this module exports
--
-- * `Structural`             — syntactic predicate "no `Agen` subterm".
-- * `nE-0→Structural`        — `nE ⟪ g ⟫ ≡ 0 → Structural g`,
--                              fully constructive.
-- * `Structural-coherence`   — the narrowed postulate: any two
--                              structural terms of the same type with
--                              isomorphic translations are `≈Term`-equal.
-- * `decode-rel-resp-≅ᴴ-atomic-compound-0E` — the original lemma,
--                              derived from the above two ingredients
--                              together with the `Atomic ⇒ Structural`
--                              fact.
--------------------------------------------------------------------------------

open import Categories.APROP
open import Categories.APROP.Hypergraph.Solver.Signature using (APROPSignatureDec)

module Categories.APROP.Hypergraph.Completeness.DecodeRel.RespIso.Discharge.AtomicCompound0E
  (sig-dec : APROPSignatureDec) where

open APROPSignatureDec sig-dec using (sig)
open APROP sig
open import Categories.APROP.Hypergraph.Core using (Hypergraph)
open import Categories.APROP.Hypergraph.FromAPROP sig using (FlatGen; ⟪_⟫)
open import Categories.APROP.Hypergraph.Iso using (_≅ᴴ_)
open import Categories.APROP.Hypergraph.Completeness.DecodeRel sig
  using (decode-rel)

open import Categories.APROP.Hypergraph.Completeness.DecodeRel.RespIso.Atomic sig-dec
  using ( Atomic
        ; atomic-Agen; atomic-id
        ; atomic-λ⇒; atomic-λ⇐; atomic-ρ⇒; atomic-ρ⇐
        ; atomic-α⇒; atomic-α⇐; atomic-σ
        )
open import Categories.APROP.Hypergraph.Completeness.DecodeRel.RespIso.AtomicCompound sig-dec
  using ( Compound
        ; compound-∘
        ; compound-⊗
        )

open import Data.Empty using (⊥; ⊥-elim)
open import Data.Nat using (ℕ; zero; suc; _+_)
open import Data.Nat.Properties using (m+n≡0⇒m≡0; m+n≡0⇒n≡0)
open import Relation.Binary.PropositionalEquality
  using (_≡_; refl)

private
  nE : Hypergraph FlatGen → ℕ
  nE = Hypergraph.nE

--------------------------------------------------------------------------------
-- The `Structural` predicate: "no `Agen` subterm anywhere".

data Structural : ∀ {A B} → HomTerm A B → Set where
  structural-id : ∀ {A} → Structural (id {A})
  structural-λ⇒ : ∀ {A} → Structural (λ⇒ {A})
  structural-λ⇐ : ∀ {A} → Structural (λ⇐ {A})
  structural-ρ⇒ : ∀ {A} → Structural (ρ⇒ {A})
  structural-ρ⇐ : ∀ {A} → Structural (ρ⇐ {A})
  structural-α⇒ : ∀ {A B C} → Structural (α⇒ {A} {B} {C})
  structural-α⇐ : ∀ {A B C} → Structural (α⇐ {A} {B} {C})
  structural-σ  : ∀ {A B} ⦃ s : Symm ≤ Symm ⦄
                → Structural (σ {A = A} {B = B} ⦃ s ⦄)
  structural-∘  : ∀ {A B C} {h : HomTerm B C} {k : HomTerm A B}
                → Structural h → Structural k
                → Structural (h ∘ k)
  structural-⊗  : ∀ {A B C D} {h : HomTerm A B} {k : HomTerm C D}
                → Structural h → Structural k
                → Structural (h ⊗₁ k)

--------------------------------------------------------------------------------
-- Atomic structural constructors are structural.  (The `Agen` atomic
-- constructor is excluded — it has `nE ≡ 1` and is handled separately.)

Atomic-non-Agen→Structural
  : ∀ {A B} {f : HomTerm A B}
  → Atomic f → nE ⟪ f ⟫ ≡ 0 → Structural f
Atomic-non-Agen→Structural (atomic-Agen _)   ()
Atomic-non-Agen→Structural atomic-id         _ = structural-id
Atomic-non-Agen→Structural atomic-λ⇒         _ = structural-λ⇒
Atomic-non-Agen→Structural atomic-λ⇐         _ = structural-λ⇐
Atomic-non-Agen→Structural atomic-ρ⇒         _ = structural-ρ⇒
Atomic-non-Agen→Structural atomic-ρ⇐         _ = structural-ρ⇐
Atomic-non-Agen→Structural atomic-α⇒         _ = structural-α⇒
Atomic-non-Agen→Structural atomic-α⇐         _ = structural-α⇐
Atomic-non-Agen→Structural (atomic-σ ⦃ s ⦄)  _ = structural-σ ⦃ s ⦄

--------------------------------------------------------------------------------
-- Main syntactic lemma: a 0-edge HomTerm is structural.
--
-- Proceeds by induction on `g`.  For atomic constructors, route via
-- `Atomic-non-Agen→Structural` (and explicitly rule out `Agen`).  For
-- compound constructors, split the additive 0 into both summands.

nE-0→Structural
  : ∀ {A B} (g : HomTerm A B) → nE ⟪ g ⟫ ≡ 0 → Structural g
nE-0→Structural (Agen _)              ()
nE-0→Structural id                    _ = structural-id
nE-0→Structural λ⇒                    _ = structural-λ⇒
nE-0→Structural λ⇐                    _ = structural-λ⇐
nE-0→Structural ρ⇒                    _ = structural-ρ⇒
nE-0→Structural ρ⇐                    _ = structural-ρ⇐
nE-0→Structural α⇒                    _ = structural-α⇒
nE-0→Structural α⇐                    _ = structural-α⇐
nE-0→Structural (σ ⦃ s ⦄)             _ = structural-σ ⦃ s ⦄
nE-0→Structural (h ∘ k) g-nE≡0 =
  -- `nE ⟪ h ∘ k ⟫ = nE ⟪ k ⟫ + nE ⟪ h ⟫` definitionally (see `nE-∘`
  -- in AtomicCompound.agda — note the order: it's `nE k + nE h`).
  structural-∘
    (nE-0→Structural h (m+n≡0⇒n≡0 (nE ⟪ k ⟫) g-nE≡0))
    (nE-0→Structural k (m+n≡0⇒m≡0 (nE ⟪ k ⟫) g-nE≡0))
nE-0→Structural (h ⊗₁ k) g-nE≡0 =
  structural-⊗
    (nE-0→Structural h (m+n≡0⇒m≡0 (nE ⟪ h ⟫) g-nE≡0))
    (nE-0→Structural k (m+n≡0⇒n≡0 (nE ⟪ h ⟫) g-nE≡0))

--------------------------------------------------------------------------------
-- Narrowed postulate: symmetric-monoidal coherence on the structural
-- fragment.
--
-- Any two structural HomTerms of the same type whose hypergraph
-- translations are isomorphic are `≈Term`-equal.  This is exactly the
-- statement of Mac Lane's symmetric-monoidal coherence theorem
-- applied to our syntactic presentation: the underlying permutation
-- is determined by the iso's boundary action, and structural terms
-- present a unique morphism per permutation up to `≈Term`.
--
-- The constructive discharge requires extending
-- `Categories.MonoidalCoherence.Solver` (currently Mac Lane only) to
-- handle the braiding σ.  See the header comment for the path.

postulate
  Structural-coherence
    : ∀ {A B} {f g : HomTerm A B}
    → Structural f → Structural g
    → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
    → decode-rel f ≈Term decode-rel g

--------------------------------------------------------------------------------
-- Discharge the original postulate.
--
-- `Atomic f` + `nE ⟪ f ⟫ ≡ 0` ⇒ `Structural f` (rules out `Agen`).
-- For the atomic shapes routed into the `…-0E` case from
-- `AtomicCompound.dispatch-structural`, the atomic-side edge count is
-- 0 by construction (see `nE-{id,λ⇒,λ⇐,ρ⇒,ρ⇐,α⇒,α⇐,σ}` there) — we
-- recover that here by case-splitting on the `Atomic` witness rather
-- than threading the edge-count proof through the API.

-- The originally-postulated lemma.  Note: the `Atomic f` hypothesis
-- combined with the dispatch from `AtomicCompound.dispatch-structural`
-- guarantees that `f` is *not* `Agen` (the Agen branch routes to
-- `decode-rel-resp-≅ᴴ-Agen-compound-1E` instead).  We extract a
-- `Structural f` witness by case-analysis on `Atomic f`, where the
-- `Agen` branch is dismissed via the iso witness's edge-count
-- transport (a `Fin 1 ↔ Fin 0` contradiction).

decode-rel-resp-≅ᴴ-atomic-compound-0E
  : ∀ {A B} {f g : HomTerm A B}
  → Atomic f → Compound g
  → nE ⟪ g ⟫ ≡ 0
  → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
  → decode-rel f ≈Term decode-rel g
decode-rel-resp-≅ᴴ-atomic-compound-0E {f = f} {g = g} af cg g-nE≡0 iso =
  Structural-coherence
    (atomic→structural af)
    (nE-0→Structural g g-nE≡0)
    iso
  where
    -- The `Agen` branch of `Atomic f` is incompatible with
    -- `⟪ f ⟫ ≅ᴴ ⟪ g ⟫` when `nE ⟪ g ⟫ ≡ 0`: the iso induces a
    -- bijection `Fin 1 ↔ Fin 0`, which is absurd.  We discharge it by
    -- routing `ψ : Fin (nE ⟪ Agen _ ⟫) → Fin (nE ⟪ g ⟫)` and then
    -- transporting along `nE ⟪ g ⟫ ≡ 0`.
    open import Data.Fin using (Fin; zero)
    open import Relation.Binary.PropositionalEquality using (subst; sym)

    Fin-zero-empty : Fin 0 → ⊥
    Fin-zero-empty ()

    -- In the `Agen` branch of `Atomic f`, the original `iso :
    -- ⟪ f ⟫ ≅ᴴ ⟪ g ⟫` becomes `⟪ Agen h ⟫ ≅ᴴ ⟪ g ⟫` (with
    -- `nE ⟪ Agen h ⟫ ≡ 1`), so `ψ zero : Fin (nE ⟪ g ⟫) = Fin 0`.
    atomic→structural : Atomic f → Structural f
    atomic→structural (atomic-Agen h) =
      ⊥-elim (Fin-zero-empty (subst Fin g-nE≡0 (_≅ᴴ_.ψ iso zero)))
    atomic→structural atomic-id        = structural-id
    atomic→structural atomic-λ⇒        = structural-λ⇒
    atomic→structural atomic-λ⇐        = structural-λ⇐
    atomic→structural atomic-ρ⇒        = structural-ρ⇒
    atomic→structural atomic-ρ⇐        = structural-ρ⇐
    atomic→structural atomic-α⇒        = structural-α⇒
    atomic→structural atomic-α⇐        = structural-α⇐
    atomic→structural (atomic-σ ⦃ s ⦄) = structural-σ ⦃ s ⦄
