{-# OPTIONS --safe --with-K #-}

--------------------------------------------------------------------------------
-- Discharge module for `final-permute-absorb` from
-- `Hypergraph.Completeness.DecodeRespIso.CompletenessAssumptions`.
--
-- ## The original field
--
-- `final-permute-absorb` is the (d) field of `CompletenessAssumptions`:
--
--   final-permute-absorb
--     : ∀ {A B} (f g : HomTerm A B) (iso : ⟪ f ⟫ ≅ᴴ ⟪ g ⟫)
--         (perm-f : proj₁ (process-all-edges ⟪ f ⟫F (Hypergraph.dom ⟪ f ⟫F))
--                   Perm.↭ Hypergraph.cod ⟪ f ⟫F)
--         (perm-g : proj₁ (process-all-edges ⟪ g ⟫F (Hypergraph.dom ⟪ g ⟫F))
--                   Perm.↭ Hypergraph.cod ⟪ g ⟫F)
--     → let stack-eq = process-edges-resp-iso-stack f g iso
--           F-vlab = Hypergraph.vlab ⟪ f ⟫F
--           G-vlab = Hypergraph.vlab ⟪ g ⟫F
--       in subst₂ HomTerm
--            (cong unflatten (sym stack-eq))
--            (cong unflatten (full-cod-eq f g))
--            (permute-via-vlab G-vlab perm-g)
--          ≈Term
--          permute-via-vlab F-vlab perm-f
--
-- ## Why this is a Mac Lane / Kelly coherence statement
--
-- `permute-via-vlab vlab p = permute (PermProp.map⁺ vlab p)` (see
-- `Hypergraph.Completeness.Permute`).  `permute` builds a HomTerm out
-- of `id, σ, α⇒, α⇐, _⊗₁_, _∘_` only — i.e. the σ-structural fragment
-- of the free symmetric monoidal category.
--
-- After the boundary `subst₂` collapses both inputs and outputs to
-- the same atom list (via `stack-eq` and `full-cod-eq f g`), the two
-- sides become two parallel HomTerms in the σ-structural fragment
-- with the SAME boundary types.  The statement "any two such terms
-- are `≈Term`-equal" is *exactly* Kelly's coherence theorem for
-- symmetric monoidal categories on the permutation fragment.
--
-- ## Why we cannot constructively close this with the existing solver
--
-- `Categories.MonoidalCoherence.Solver.solveM` mechanises Mac Lane's
-- coherence theorem for *monoidal* categories — its fragment is
-- `id, α, λ, ρ, _⊗₁_, _∘_` (no σ).  Adding σ requires the symmetric
-- (a.k.a. permutative) coherence theorem, which has not yet been
-- mechanised in `Categories.MonoidalCoherence`.  See the analysis in
-- `Hypergraph.Completeness.DecodeRel.RespIso.Discharge.AtomicCompound0E`
-- (header) for the same conclusion in a parallel context.
--
-- ## Discharge strategy used here
--
-- We expose a *single* narrow sub-assumption
-- `PermuteCoherence`: any two `permute p` and `permute q` HomTerms
-- between the *same* atom lists are `≈Term`-equal.  This is strictly
-- narrower than the original `final-permute-absorb`:
--
--   * No mention of `f, g, iso, ⟪_⟫F`, the Translation iso, or the
--     decoder/process-edges machinery.
--   * No `subst₂` plumbing — it is a plain `≈Term` statement
--     between two HomTerms over identical boundary types.
--   * It is exactly the statement of symmetric monoidal coherence
--     on the `permute` fragment (the σ-structural permutation
--     morphisms generated by `id, σ, α, _⊗₁_, _∘_`).
--
-- The narrowed assumption is exposed as a record `PermuteCoherence`
-- and a `--safe`-clean module `WithCoherence` parameterised by it.
-- This mirrors the structure of `CompletenessAssumptions` in
-- `DecodeRespIso`: no new `postulate` is introduced inside this
-- module; a downstream consumer chooses whether to construct or
-- postulate the witness.
--
-- The original `final-permute-absorb` follows by:
--   (1) Aligning the underlying atom lists via `subst₂` on both sides
--       using `stack-eq` and `full-cod-eq f g`.
--   (2) Observing that, *after* alignment, the two sides are
--       `permute p` and `permute q` for some `p, q` over the same
--       (post-aligned) lists; applying the coherence witness.
--
-- ## Trust delta
--
-- Original: `final-permute-absorb` — 7 implicit args + iso + 2
-- permutations + boundary subst₂ over `HomTerm`-indexed by the
-- algorithmic decoder.
--
-- Narrowed: `PermuteCoherence` — single field: 2 implicit `List X`
-- args + 2 permutation proofs.  No iso, no decoder plumbing, no
-- FromAPROP.  This is the *minimal* assumption carrying the symmetric
-- monoidal coherence content.
--------------------------------------------------------------------------------

open import Categories.APROP
open import Categories.APROP.Hypergraph.Solver.Signature using (APROPSignatureDec)

module Categories.APROP.Hypergraph.Completeness.Discharge.FinalPermute
  (sig-dec : APROPSignatureDec) where

open APROPSignatureDec sig-dec using (sig)
open APROP sig

open import Categories.APROP.Hypergraph.Core using (Hypergraph; codL)
open import Categories.APROP.Hypergraph.FromAPROP sig
  renaming (⟪_⟫ to ⟪_⟫F; ⟪⟫-codL to ⟪⟫F-codL)
open import Categories.APROP.Hypergraph.Translation sig using (⟪_⟫)
open import Categories.APROP.Hypergraph.Iso using (_≅ᴴ_)
open import Categories.APROP.Hypergraph.Completeness.Unflatten sig
  using (unflatten)
open import Categories.APROP.Hypergraph.Completeness.Decode sig
  using (process-all-edges)
open import Categories.APROP.Hypergraph.Completeness.Permute sig
  using (permute; permute-via-vlab)

open import Data.Fin using (Fin)
open import Data.List using (List; map)
import Data.List.Relation.Binary.Permutation.Propositional as Perm
import Data.List.Relation.Binary.Permutation.Propositional.Properties as PermProp
open import Data.Product using (proj₁)
open import Relation.Binary.PropositionalEquality
  using (_≡_; refl; sym; trans; cong; subst₂)

--------------------------------------------------------------------------------
-- Local helper: full-cod-eq.  Inlined here from DecodeRespIso to keep
-- this discharge module minimal-dependency.  Constructive (no K
-- needed, just trans+sym).

private
  full-cod-eq : ∀ {A B} (f g : HomTerm A B)
              → codL ⟪ g ⟫F ≡ codL ⟪ f ⟫F
  full-cod-eq f g = trans (⟪⟫F-codL g) (sym (⟪⟫F-codL f))

--------------------------------------------------------------------------------
-- The narrowed sub-assumption: symmetric monoidal coherence on the
-- `permute` fragment.
--
-- This is exactly Kelly's coherence theorem for symmetric monoidal
-- categories restricted to morphisms built from `id, σ, α, _⊗₁_, _∘_`.
-- It says: any two propositional permutation derivations of the same
-- pair of atom lists produce `≈Term`-equal HomTerms via `permute`.
--
-- ### Why it is genuinely irreducible (given existing infrastructure):
--
-- `permute` is recursive on `_↭_`, which is NOT a thin relation:
-- `Perm.refl` and `Perm.trans Perm.refl Perm.refl` are distinct
-- derivations of the same underlying list permutation, yet `permute`
-- produces propositionally distinct HomTerms (`id` vs `id ∘ id`),
-- which are only `≈Term`-equal (via `idˡ`).  Mac Lane's coherence
-- *theorem* says these merging issues are uniform: any two
-- derivations are equivalent up to the coherence axioms.  But the
-- *proof* requires either:
--
--   (a) An extended `solveM` covering the symmetric (σ) case (Kelly's
--       theorem), which is not yet mechanised in
--       `Categories.MonoidalCoherence`.
--   (b) A direct quotient construction interpreting `FreeMonoidal`
--       in a model where structural morphisms agree iff they realize
--       the same list permutation — substantial development.
--
-- We therefore expose this single fact as a record field; a
-- downstream consumer postulates it once, and this module discharges
-- `final-permute-absorb` from it constructively.

record PermuteCoherence : Set where
  field
    permute-≈Term-coherence
      : ∀ {xs ys : List X} (p q : xs Perm.↭ ys)
      → permute p ≈Term permute q

--------------------------------------------------------------------------------
-- ## Constructive discharge, parameterised by the coherence witness.

module WithCoherence (coh : PermuteCoherence) where
  open PermuteCoherence coh

  ------------------------------------------------------------------------
  -- Lift coherence through `permute-via-vlab`.
  --
  -- `permute-via-vlab vlab p = permute (PermProp.map⁺ vlab p)`.  So any
  -- two `permute-via-vlab vlab p` and `permute-via-vlab vlab q` are
  -- `≈Term`-equal by `permute-≈Term-coherence` applied to
  -- `map⁺ vlab p` and `map⁺ vlab q`.

  permute-via-vlab-≈Term-coherence
    : ∀ {n} {xs ys : List (Fin n)}
        (vlab : Fin n → X)
        (p q : xs Perm.↭ ys)
    → permute-via-vlab vlab p ≈Term permute-via-vlab vlab q
  permute-via-vlab-≈Term-coherence vlab p q =
    permute-≈Term-coherence (PermProp.map⁺ vlab p) (PermProp.map⁺ vlab q)

  ------------------------------------------------------------------------
  -- The discharge itself.
  --
  -- Both sides of the goal — once boundary `subst₂` is applied — live
  -- in the same hom-set `HomTerm (unflatten (map F-vlab (proj₁ proc-F)))
  -- (unflatten (codL ⟪ f ⟫F))`.
  --
  -- The strategy is to J-eliminate the two boundary equalities
  -- (`stack-eq` and `full-cod-eq f g`) inside a generic helper that
  -- reduces the subst₂ to identity, then appeal to the coherence
  -- witness.
  --
  -- We split out the iso-free *generic* discharge first; the actual
  -- `final-permute-absorb` then plugs in the specific equalities.

  -- Generic version: any two parallel atom-list permutation
  -- derivations whose boundaries match propositionally produce
  -- ≈Term-equal `permute` HomTerms under the appropriate subst₂.
  generic-permute-absorb
    : ∀ {as bs cs ds : List X}
        (as≡bs : as ≡ bs) (ds≡cs : ds ≡ cs)
        (p : as Perm.↭ cs) (q : bs Perm.↭ ds)
    → subst₂ HomTerm
        (cong unflatten (sym as≡bs))
        (cong unflatten ds≡cs)
        (permute q)
      ≈Term permute p
  generic-permute-absorb refl refl p q = permute-≈Term-coherence q p

  ------------------------------------------------------------------------
  -- The constructive discharge of `final-permute-absorb`.
  --
  -- Takes `stack-eq` and the two permutation witnesses as parameters
  -- (rather than the iso plus a (b)-field appeal) so the discharge
  -- composes cleanly with whatever wiring the WithAssumptions module
  -- in `DecodeRespIso` uses for the (b) field.

  final-permute-absorb-discharge
    : ∀ {A B} (f g : HomTerm A B) (iso : ⟪ f ⟫ ≅ᴴ ⟪ g ⟫)
        (stack-eq :
            map (Hypergraph.vlab ⟪ f ⟫F)
                (proj₁ (process-all-edges ⟪ f ⟫F (Hypergraph.dom ⟪ f ⟫F)))
          ≡
            map (Hypergraph.vlab ⟪ g ⟫F)
                (proj₁ (process-all-edges ⟪ g ⟫F (Hypergraph.dom ⟪ g ⟫F))))
        (perm-f : proj₁ (process-all-edges ⟪ f ⟫F (Hypergraph.dom ⟪ f ⟫F))
                  Perm.↭ Hypergraph.cod ⟪ f ⟫F)
        (perm-g : proj₁ (process-all-edges ⟪ g ⟫F (Hypergraph.dom ⟪ g ⟫F))
                  Perm.↭ Hypergraph.cod ⟪ g ⟫F)
    → let F-vlab = Hypergraph.vlab ⟪ f ⟫F
          G-vlab = Hypergraph.vlab ⟪ g ⟫F
      in subst₂ HomTerm
           (cong unflatten (sym stack-eq))
           (cong unflatten (full-cod-eq f g))
           (permute-via-vlab G-vlab perm-g)
         ≈Term
         permute-via-vlab F-vlab perm-f
  final-permute-absorb-discharge {A} {B} f g iso stack-eq perm-f perm-g =
    let F-vlab = Hypergraph.vlab ⟪ f ⟫F
        G-vlab = Hypergraph.vlab ⟪ g ⟫F
        mapped-perm-f = PermProp.map⁺ F-vlab perm-f
        mapped-perm-g = PermProp.map⁺ G-vlab perm-g
        cod-eq = full-cod-eq f g
    in generic-permute-absorb stack-eq cod-eq mapped-perm-f mapped-perm-g

  ------------------------------------------------------------------------
  -- ## Drop-in replacement matching the original field signature.
  --
  -- The original (d) field in `CompletenessAssumptions` references
  -- `process-edges-resp-iso-stack f g iso` (the (b) field) inside the
  -- type via a let-binding.  To produce a discharge with that exact
  -- type, we parametrise on the (b) callback.  A consumer that has
  -- the (b) field (e.g. from `CompletenessAssumptions`) can then call
  -- `from-stack-callback` to get exactly the original field value.

  module FromStackCallback
    (stack-callback
      : ∀ {A B} (f g : HomTerm A B) → ⟪ f ⟫ ≅ᴴ ⟪ g ⟫
      → map (Hypergraph.vlab ⟪ f ⟫F)
            (proj₁ (process-all-edges ⟪ f ⟫F (Hypergraph.dom ⟪ f ⟫F)))
      ≡ map (Hypergraph.vlab ⟪ g ⟫F)
            (proj₁ (process-all-edges ⟪ g ⟫F (Hypergraph.dom ⟪ g ⟫F))))
    where

    -- Exact drop-in matching the (d) field's type modulo `let`-unfolding:
    --   given (f, g, iso, perm-f, perm-g), produce the ≈Term.
    final-permute-absorb
      : ∀ {A B} (f g : HomTerm A B) (iso : ⟪ f ⟫ ≅ᴴ ⟪ g ⟫)
          (perm-f : proj₁ (process-all-edges ⟪ f ⟫F (Hypergraph.dom ⟪ f ⟫F))
                    Perm.↭ Hypergraph.cod ⟪ f ⟫F)
          (perm-g : proj₁ (process-all-edges ⟪ g ⟫F (Hypergraph.dom ⟪ g ⟫F))
                    Perm.↭ Hypergraph.cod ⟪ g ⟫F)
      → let stack-eq = stack-callback f g iso
            F-vlab = Hypergraph.vlab ⟪ f ⟫F
            G-vlab = Hypergraph.vlab ⟪ g ⟫F
        in subst₂ HomTerm
             (cong unflatten (sym stack-eq))
             (cong unflatten (full-cod-eq f g))
             (permute-via-vlab G-vlab perm-g)
           ≈Term
           permute-via-vlab F-vlab perm-f
    final-permute-absorb f g iso perm-f perm-g =
      final-permute-absorb-discharge f g iso
        (stack-callback f g iso) perm-f perm-g
